# SPDX-FileCopyrightText: 2025 Eris <eris@erisws.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <123355664+sleepyyapril@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: antag
  id: Changeling
  name: roles-antag-changeling-name
  antagonist: true
  setPreference: true
  objective: roles-antag-changeling-description
  requirements:
  - !type:SpeciesRequirement
    inverted: true
    species:
    - IPC
