# SPDX-FileCopyrightText: 2021 Timrod <timrod@gmail.com>
# SPDX-FileCopyrightText: 2022 Kara <lunarautomaton6@gmail.com>
# SPDX-FileCopyrightText: 2022 Moony <moonheart08@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Chief-Engineer <119664036+Chief-Engineer@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Emisse <99158783+Emisse@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Fluffiest Floofers <thebluewulf@gmail.com>
# SPDX-FileCopyrightText: 2023 Moony <moony@hellomouse.net>
# SPDX-FileCopyrightText: 2023 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Velcroboy <107660393+IamVelcroboy@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 John Willis <143434770+CerberusWolfie@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Jonathan <44554691+Mike32oz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Mike32oz <44554691+Mike32oz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <123355664+sleepyyapril@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <flyingkarii@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: gameMap
  id: Meta
  mapName: 'Meta Station'
  mapPath: /Maps/TheDen/meta.yml
  minPlayers: 20 #
  maxPlayers: 85 #
  stations:
    Meta:
      stationProto: StandardNanotrasenStation
      components:
        - type: StationNameSetup
          mapNameTemplate: '{0} Meta Station {1}'
          nameGenerator:
            !type:NanotrasenNameGenerator
            prefixCreator: 'TG'
        - type: StationEmergencyShuttle
          emergencyShuttlePath: /Maps/Shuttles/emergency_meta.yml
        - type: StationJobs
          availableJobs:
            #service
            Captain: [ 1, 1 ]
            BlueshieldOfficer: [ 1, 1]
            NanotrasenRepresentative: [ 1, 1 ]
            Magistrate: [ 1, 1 ]
            AdministrativeAssistant: [ 1, 1 ]
            HeadOfPersonnel: [ 1, 1 ]
            Bartender: [ 2, 2 ]
            Botanist: [ 2, 3 ]
            Chef: [ 2, 2 ]
            Janitor: [ 1, 3 ]
            Librarian: [ 1, 1 ]
            ServiceWorker: [ 2, 3 ]
            #engineering
            ChiefEngineer: [ 1, 1 ]
            SeniorEngineer: [ 1, 1 ]
            AtmosphericTechnician: [ 3, 3 ]
            StationEngineer: [ 5, 7 ]
            TechnicalAssistant: [ 3, 6 ]
            #medical
            ChiefMedicalOfficer: [ 1, 1 ]
            SeniorPhysician: [ 1, 1 ]
            Chemist: [ 3, 3 ]
            MedicalDoctor: [ 5, 5 ]
            MedicalIntern: [ 3, 6 ]
            Paramedic: [ 1, 3 ]
            #science
            ResearchDirector: [ 1, 1 ]
            Scientist: [ 5, 7 ]
            ResearchAssistant: [ 3, 6 ]
            Chaplain: [ 1, 1 ]
            Roboticist: [ 1, 2 ]
            ForensicMantis: [ 1, 1 ]
            SeniorResearcher: [ 1, 1 ]
            #security
            HeadOfSecurity: [ 1, 1 ]
            Warden: [ 1, 1 ]
            SecurityOfficer: [ 5, 7 ]
            Detective: [ 1, 1 ]
            SecurityCadet: [ 3, 6 ]
            Lawyer: [ 2, 2 ]
            Brigmedic: [ 1, 1 ]
            Prisoner: [ 1, 2 ]
            PrisonGuard: [ 1, 1 ]
            SeniorOfficer: [ 1, 1 ]
            #supply
            Quartermaster: [ 1, 1 ]
            SalvageSpecialist: [ 3, 3 ]
            CargoTechnician: [ 3, 5 ]
            MailCarrier: [ 1, 2 ]
            #civilian
            Passenger: [ -1, -1 ]
            Clown: [ 1, 1 ]
            Mime: [ 1, 1 ]
            Musician: [ 1, 2 ]
            Reporter: [ 2, 2 ]
            #silicon
            Borg: [ 2, 2 ]
            MedicalBorg: [ 2, 2 ]
            StationAi: [ 1, 1 ]
