- type: loadout
  id: LoadoutCommandHOSJumpsuit
  category: JobsSecurityHeadOfSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityUniforms
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingUniformJumpsuitHoS

- type: loadout
  id: LoadoutCommandHOSJumpskirt
  category: JobsSecurityHeadOfSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityUniforms
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingUniformJumpskirtHoS
