// SPDX-FileCopyrightText: 2023 Nemanja
// SPDX-FileCopyrightText: 2023 Vasilis
// SPDX-FileCopyrightText: 2024 Aexxie
// SPDX-FileCopyrightText: 2024 Debug
// SPDX-FileCopyrightText: 2024 FoxxoTrystan
// SPDX-FileCopyrightText: 2024 Psychpsyo
// SPDX-FileCopyrightText: 2024 SimpleStation14
// SPDX-FileCopyrightText: 2024 Sk1tch
// SPDX-FileCopyrightText: 2024 SlamBamActionman
// SPDX-FileCopyrightText: 2024 Spatison
// SPDX-FileCopyrightText: 2024 deathride58
// SPDX-FileCopyrightText: 2024 metalgearsloth
// SPDX-FileCopyrightText: 2025 Dirius77
// SPDX-FileCopyrightText: 2025 DocNITE
// SPDX-FileCopyrightText: 2025 Falcon
// SPDX-FileCopyrightText: 2025 RedFoxIV
// SPDX-FileCopyrightText: 2025 portfiend
// SPDX-FileCopyrightText: 2025 sev7ves
// SPDX-FileCopyrightText: 2025 sleepyyapril
//
// SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

using System.Linq;
using Content.Client.UserInterface.Screens;
using Content.Shared._DEN.CCVars;
using Content.Shared._DV.CCVars;
using Content.Shared._Impstation.CCVar;
using Content.Shared.CCVar;
using Content.Shared.HUD;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Configuration;
using Robust.Shared.Network;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Range = Robust.Client.UserInterface.Controls.Range;

namespace Content.Client.Options.UI.Tabs
{
    [GenerateTypedNameReferences]
    public sealed partial class DenTab : Control
    {
        [Dependency] private readonly IConfigurationManager _cfg = default!;

        public DenTab()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            AutoFormatterEnabled.OnToggled += OnCheckBoxToggled;
            RemoveAsterisksFromEmotes.OnToggled += OnCheckBoxToggled;
            ShowTypingRangeOnShortRange.OnToggled += OnCheckBoxToggled;

            ApplyButton.OnPressed += OnApplyButtonPressed;
            UpdateApplyButton();
        }

        private void OnCheckBoxToggled(BaseButton.ButtonToggledEventArgs args) => UpdateApplyButton();

        private void OnApplyButtonPressed(BaseButton.ButtonEventArgs args)
        {
            _cfg.SetCVar(DenCCVars.AutoFormatterEnabled, AutoFormatterEnabled.Pressed);
            _cfg.SetCVar(DenCCVars.RemoveAsterisksFromEmotes, RemoveAsterisksFromEmotes.Pressed);
            _cfg.SetCVar(DenCCVars.ShowTypingRange, ShowTypingRangeOnShortRange.Pressed);

            _cfg.SaveToFile();
            UpdateApplyButton();
        }

        private void UpdateApplyButton()
        {
            var isAutoFormatterSame = AutoFormatterEnabled.Pressed == _cfg.GetCVar(DenCCVars.AutoFormatterEnabled);
            var isRemoveAsterisksSame = RemoveAsterisksFromEmotes.Pressed == _cfg.GetCVar(DenCCVars.RemoveAsterisksFromEmotes);
            var isShowTypingRangeSame = ShowTypingRangeOnShortRange.Pressed == _cfg.GetCVar(DenCCVars.ShowTypingRange);

            ApplyButton.Disabled = isAutoFormatterSame &&  isRemoveAsterisksSame && isShowTypingRangeSame;
        }

    }

}
