# SPDX-FileCopyrightText: 2024 Mnemotechnican <69920617+Mnemotechnician@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <123355664+sleepyyapril@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: Interaction
  id: Base
  abstract: true
  effectSuccess:
    popup: Small
  effectFailure:
    popup: SubtleFail

# Base global interaction
- type: Interaction
  id: BaseGlobal
  abstract: true
  global: true

# Base interaction that involves hands
- type: Interaction
  id: BaseHands
  abstract: true
  requiresHands: true
  requiresCanInteract: true
  contactInteraction: true
  range:
    max: 1.2
  effectSuccess:
    popup: Obvious
    sound: {path: /Audio/Effects/thudswoosh.ogg}
  effectFailure:
    popup: Fail
    sound: {path: /Audio/Effects/thudswoosh.ogg}

# Base interaction using dangerous popups
- type: Interaction
  id: BaseDangerous
  abstract: true
  effectSuccess:
    popup: Dangerous
    sound: {path: /Audio/Effects/thudswoosh.ogg}
  effectFailure:
    popup: Fail
    sound: {path: /Audio/Effects/thudswoosh.ogg}
  effectDelayed:
    popup: DangerousDelayed
