- type: entity
  id: MiniGyroscopeMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: mini gyroscope machine board
  components:
  - type: MachineBoard
    prototype: MiniGyroscope
    requirements:
      Manipulator: 1
      Capacitor: 1
    materialRequirements: 
      Glass: 2

# - type: entity
#   id: ServiceTechFabCircuitboard
#   parent: BaseMachineCircuitboard
#   name: service techfab machine board
#   description: A machine printed circuit board for a Service techfab.
#   components:
#     - type: Sprite
#       state: service
#     - type: MachineBoard
#       prototype: ServiceTechFab
#       stackRequirements:
#         MatterBin: 2
#         Manipulator: 2
#       tagRequirements:
#         GlassBeaker:
#           amount: 2
#           defaultPrototype: Beaker
#     - type: StealTarget
#       stealGroup: ServiceTechFab

- type: entity
  id: ImpCoffeeMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: spacepresso machine board
  description: A machine printed circuit board for a spacepresso machine.
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: ImpCoffeeMachineEmpty
      materialRequirements:
        Steel: 5
      tagRequirements:
          GlassBeaker:
            Amount: 1
            DefaultPrototype: Beaker
