# SPDX-FileCopyrightText: 2020 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 2025 BlitzTheSquishy <73762869+BlitzTheSquishy@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 TheDen-Bot <thelargetrucksyndicate@gmail.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <123355664+sleepyyapril@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

Project-Condor:
  org: space-wizards
  project: 2
  inbox: Inbox
  labels:
    "W: In Progress": "In Progress"
    "W: Discussion": "Design and Discussion"
    "W: Backlog": "Backlog"
    "W: Next": "Next"
