# SPDX-FileCopyrightText: 2023 Fluffiest Floofers <thebluewulf@gmail.com>
# SPDX-FileCopyrightText: 2025 EctoplasmIsGood <109397347+EctoplasmIsGood@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <123355664+sleepyyapril@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

# The vector is no more
# - type: entity
#  parent: GunSafe
#  id: GunSafeSubMachineGunVector
#  name: vector safe
#  components:
#  - type: StorageFill
#    contents:
#    - id: WeaponSubMachineGunVector
#      amount: 2
#    - id: MagazineMagnumSubMachineGun
#      amount: 4
