# SPDX-FileCopyrightText: 2024 gluesniffler
# SPDX-FileCopyrightText: 2025 CometVoid
# SPDX-FileCopyrightText: 2025 MajorMoth
# SPDX-FileCopyrightText: 2025 Sir Warock
# SPDX-FileCopyrightText: 2025 pathetic meowmeow
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: entity
  parent: BaseMachineCircuitboard
  id: AutodocCircuitboard
  name: autodoc machine board
  description: A machine printed circuit board for an autodoc.
  components:
  - type: MachineBoard
    prototype: Autodoc
    requirements:
      Manipulator: 4
    materialRequirements:
      Cable: 3
      Steel: 10
    tagRequirements:
      BorgArm:
        Amount: 3
        ExamineName: "Borg Arm"
        DefaultPrototype: LeftArmBorg

- type: entity
  parent: AutodocCircuitboard
  id: AutodocSyndieCircuitboard
  suffix: Syndie
  components:
  - type: MachineBoard
    prototype: AutodocSyndie

- type: entity
  parent: BaseMachineCircuitboard
  id: OperatingTableCircuitboard
  name: operating table machine board
  description: A machine printed circuit board for an operating table.
  components:
  - type: MachineBoard
    prototype: OperatingTable
    materialRequirements:
      Cable: 3
      Silver: 2
      Steel: 4

- type: entity
  id: MedicalBiofabMachineBoard
  parent: BaseMachineCircuitboard
  name: medical biofab machine board
  description: A machine printed circuit board for a medical biofab.
  components:
  - type: Sprite
    state: medical
  - type: MachineBoard
    prototype: MedicalBiofabricator
    requirements:
      MatterBin: 2
      Manipulator: 2

- type: entity
  parent: BaseMachineCircuitboard
  id: OperatingTableAdvancedCircuitboard
  name: advanced operating table machine board
  description: A machine printed circuit board for an advanced operating table.
  components:
  - type: MachineBoard
    prototype: OperatingTableAdvanced
    materialRequirements:
      Cable: 3
      Silver: 2
      Steel: 4
