- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:CharacterPlaytimeRequirement
      tracker: JobQuartermaster # DeltaV - Logistics Department replacing Cargo
      min: 7200 # The Den - 2 hour
    - !type:CharacterPlaytimeRequirement
      tracker: JobChiefEngineer
      min: 7200 # The Den - 2 hour
    - !type:CharacterPlaytimeRequirement
      tracker: JobChiefMedicalOfficer
      min: 7200 # The Den - 2 hour
    - !type:CharacterPlaytimeRequirement
      tracker: JobHeadOfSecurity
      min: 7200 # The Den - 2 hour
    - !type:CharacterPlaytimeRequirement # DeltaV - Epistemics dept time requirement
      tracker: JobResearchDirector # DeltaV - Epistemics Department replacing Science
      min: 7200 # The Den - 2 hour
    - !type:CharacterPlaytimeRequirement # DeltaV - Epistemics dept time requirement
      tracker: JobHeadOfPersonnel # DeltaV - Epistemics Department replacing Science
      min: 7200 # The Den - 2 hour
    - !type:CharacterOverallTimeRequirement
      min: 144000 # The Den - 40 hour
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: CaptainGear
  subGear:
  - CaptainPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCaptain
    back: ClothingBackpackCaptainFilled
    shoes: ClothingShoesBootsLaceup
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  innerClothingSkirt: ClothingUniformJumpskirtCaptain
  satchel: ClothingBackpackSatchelCaptainFilled
  duffelbag: ClothingBackpackDuffelCaptainFilled

- type: startingGear
  id: CaptainPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitCaptain
    head: ClothingHeadEnvirohelmCaptain
    gloves: ClothingHandsGlovesCaptain
