- type: latheRecipe
  abstract: true
  id: BaseCarpetRecipe
  category: Carpet
  completetime: 1
  materials:
    Cloth: 100

- type: latheRecipe
  abstract: true
  parent: BaseJumpsuitRecipe
  id: BaseJumpsuitGenericRecipe
  category: ColoredUniforms

- type: latheRecipe
  abstract: true
  parent: BaseJumpsuitRecipe
  id: BaseJumpsuitLoadoutRecipe
  category: LoadoutJumpsuits

- type: latheRecipe
  abstract: true
  parent: BaseJumpsuitRecipe
  id: BaseJumpsuitLoadoutDressRecipe
  category: LoadoutDresses

- type: latheRecipe
  abstract: true
  parent: BaseJumpsuitRecipe
  id: BaseJumpsuitEnvirosuitRecipe
  category: Envirosuits

- type: latheRecipe
  abstract: true
  parent: BaseHatRecipe
  id: BaseHatEnvirohelmRecipe
  category: Envirosuits
