// SPDX-FileCopyrightText: 2025 Dirius77
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.Lobby.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._DEN.Job;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;


namespace Content.Client._DEN.Lobby.UI.Controls;

/// <summary>
///     A selection of job titles for this job.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class AlternateTitleSelectionMenu : FancyWindow
{
    public event Action<string?>? OnSelectedAlternateTitleChanged;

    public AlternateTitleSelectionMenu(JobPrototype job,
        List<string> titles,
        string? selectedAlternateTitle = null)
    {
        RobustXamlLoader.Load(this);

        var buttons = new List<string> { job.ID, };
        buttons.AddRange(titles);

        var selector = new RadioOptions<string>(RadioOptionsLayout.Vertical);

        foreach (var titleId in buttons)
        {
            var title = GetButtonText(job, titleId);

            selector.AddItem(title, titleId, _ => OnSelectedAlternateTitleChanged?.Invoke(titleId));
            if (selectedAlternateTitle != null && titleId == selectedAlternateTitle)
                selector.SelectByValue(titleId);
        }

        TitlesContainer.AddChild(selector);
        Titles.InvalidateMeasure();
    }

    private string GetButtonText(JobPrototype job, string title) =>
        title == job.ID ? job.LocalizedName : title;

}
