// SPDX-FileCopyrightText: 2025 portfiend
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Resources;
using Content.Shared.Clothing.Loadouts.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Lobby.UI.Controls;

// This basically exists just to cut out a lot of style-setting boilerplate.
[GenerateTypedNameReferences]
public sealed partial class LoadoutCategoryList : BoxContainer
{
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    private const string CategoryNameFontPath = "/Fonts/NotoSans/NotoSans-Bold.ttf";
    private const int CategoryNameFontSize = 16;
    private Font CategoryNameFont => _resourceCache.GetFont(CategoryNameFontPath, CategoryNameFontSize);

    public LoadoutCategoryPrototype? FirstLeafCategory;
    public Button? FirstLeafButton;

    public LoadoutCategoryList()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        CategoryTitleLabel.FontOverride = CategoryNameFont;
    }

    public void SetLabelText(string name)
    {
        CategoryTitleLabel.Text = name;
    }
}
