// SPDX-FileCopyrightText: 2025 portfiend
//
// SPDX-License-Identifier: AGPL-3.0-or-later


using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Lobby.UI.Controls;

// This basically exists just to cut out a lot of style-setting boilerplate.
[GenerateTypedNameReferences]
public sealed partial class LoadoutCategoryButton : Button
{
    private const string BranchButtonStyleClass = StyleNano.StyleClassAltButton;

    private bool _isLeaf = false;
    private string _labelText = string.Empty;
    private int _loadoutCount = 0;

    public LoadoutCategoryButton(bool leaf)
    {
        RobustXamlLoader.Load(this);

        _isLeaf = leaf;
        ToggleMode = _isLeaf;

        if (!_isLeaf)
            AddStyleClass(BranchButtonStyleClass);
    }

    public void SetLabelText(string text)
    {
        _labelText = text;
        UpdateLabel();
    }

    public void SetLoadoutCount(int count)
    {
        _loadoutCount = count;
        UpdateLabel();
    }

    private void UpdateLabel()
    {
        var text = _labelText;

        if (_loadoutCount != 0)
            text += $" ({_loadoutCount})";

        // TODO: Find a better way to denote branches/categories.
        if (!_isLeaf)
            text += " ...";

        Label.Text = text;
    }
}
