
using System.Linq;
using System.Text;
using Content.Client.Stylesheets;
using Content.Shared.Clothing.Loadouts.Prototypes;
using Content.Shared.Clothing.Loadouts.Systems;
using Content.Shared.Labels.Components;
using Content.Shared.Paint;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._DEN.Lobby.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class LoadoutItemButton : BoxContainer
{
    [Dependency] private readonly IEntityManager _entity = default!;

    private readonly SharedAppearanceSystem _appearance;

    /// <summary>
    ///     Fired when this button's loadout preference changes (on/off, appearance, etc).
    /// </summary>
    public event Action<LoadoutPreference>? OnPreferenceChanged;

    /// <summary>
    ///     Fired when the "customize" button is clicked for this button.
    /// </summary>
    public event Action<ProtoId<LoadoutPrototype>>? OnCustomizeToggled;

    private const string CustomizeButtonStyleClass = StyleNano.StyleClassAltButton;
    private const string UnwearableStyleClass = StyleBase.ButtonCaution;
    private const string UnusableStyleClass = StyleBase.ButtonDanger;
    private const float MaxTooltipWidth = 650f;

    private readonly Thickness _customizeButtonPadding = new Thickness(5, 0);

    // Dependencies
    // Events
    // Constants
    // Data Lists
    // Private Class Members
    // Public Variables
    // Dynamic Private Variables

    public LoadoutPrototype Loadout;
    public bool Pressed => ItemToggleButton.Pressed;
    public bool Unusable => ItemToggleButton.HasStyleClass(UnusableStyleClass);
    public bool Unwearable => ItemToggleButton.HasStyleClass(UnwearableStyleClass);
    public string LoadoutName => LoadoutNameLabel.Text ?? string.Empty;

    /// <summary>
    ///     Whether or not this button matches the current search filter.
    ///     Used externally.
    /// </summary>
    public bool MatchFilter = true;

    private LoadoutPreference _preference;

    public LoadoutPreference Preference
    {
        get => _preference;
        set
        {
            _preference = value;
            ItemToggleButton.Pressed = value.Selected;
            UpdatePressedVisuals();
            UpdatePaint();
        }
    }

    public EntityUid? PreviewEntity { get; private set; }

    public LoadoutItemButton(LoadoutPrototype loadout)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        _appearance = _entity.System<SharedAppearanceSystem>();

        CustomizeButton.AddStyleClass(CustomizeButtonStyleClass);
        CustomizeButton.Label.Margin = _customizeButtonPadding;

        Loadout = loadout;
        InitPreview();
        Preference = _preference = new(Loadout.ID);


        LoadoutNameLabel.Text = GetName();
        CostLabel.Text = Loadout.Cost.ToString();

        ItemToggleButton.OnToggled += OnButtonToggled;
        ItemToggleButton.OnToggled += _ => UpdatePressedVisuals();
        CustomizeButton.OnPressed += _ => OnCustomizeToggled?.Invoke(Loadout.ID);
    }

    protected override void Deparented()
    {
        if (PreviewEntity != null)
            _entity.QueueDeleteEntity(PreviewEntity);

        base.Deparented();
    }

    public void SetUnusable(bool unusable, List<string> reasons)
    {
        SetStyleClass(UnusableStyleClass, unusable);

        var tooltipText = new StringBuilder();
        var desc = GetDescription();

        if (!string.IsNullOrEmpty(desc))
            tooltipText.Append(desc);

        if (reasons.Count > 0)
            tooltipText.Append("\n");

        foreach (var reason in reasons)
            tooltipText.Append($"\n{reason}");

        if (tooltipText.Length == 0)
            return;

        var formattedTooltip = new Tooltip();
        formattedTooltip.MaxWidth = MaxTooltipWidth;

        var message = FormattedMessage.FromMarkupPermissive(tooltipText.ToString());
        formattedTooltip.SetMessage(message);
        ItemToggleButton.TooltipSupplier = _ => formattedTooltip;
    }

    public void SetUnwearable(bool unwearable)
    {
        SetStyleClass(UnwearableStyleClass, unwearable);
    }

    public void SetStyleClass(string styleClass, bool enabled)
    {
        if (enabled && !ItemToggleButton.HasStyleClass(styleClass))
            ItemToggleButton.AddStyleClass(styleClass);
        else if (!enabled && ItemToggleButton.HasStyleClass(styleClass))
            ItemToggleButton.RemoveStyleClass(styleClass);
    }

    private void InitPreview()
    {
        if (PreviewEntity != null)
            _entity.QueueDeleteEntity(PreviewEntity);

        var previewProto = Loadout.Items.First();
        PreviewEntity = _entity.Spawn(previewProto, MapCoordinates.Nullspace);
        PreviewSprite.SetEntity(PreviewEntity);
    }

    private void UpdatePressedVisuals()
    {
        CustomizeButton.Visible = ItemToggleButton.Pressed;
    }

    private void UpdatePaint()
    {
        if (!Preference.Selected || PreviewEntity == null || !Loadout.CustomColorTint)
            return;

        var hasColor = _preference.CustomColorTint != null;
        var appearance = _entity.EnsureComponent<AppearanceComponent>(PreviewEntity.Value);
        if (hasColor)
        {
            var paint = _entity.EnsureComponent<PaintedComponent>(PreviewEntity.Value);
            paint.Enabled = true;
            paint.Color = Color.FromHex(_preference.CustomColorTint);
        }
        else
            _entity.RemoveComponent<PaintedComponent>(PreviewEntity.Value);

        _appearance.TryGetData(PreviewEntity.Value, PaintVisuals.Painted, out bool isPainted, appearance);
        _appearance.SetData(PreviewEntity.Value, PaintVisuals.Painted, !isPainted, appearance);
    }

    private void OnButtonToggled(BaseButton.ButtonToggledEventArgs args)
    {
        _preference.Selected = args.Pressed;
        OnPreferenceChanged?.Invoke(_preference);
    }

    public void SetSelected(bool selected)
    {
        _preference.Selected = selected;
        ItemToggleButton.Pressed = selected;
        UpdatePressedVisuals();
    }

    private string GetName()
    {
        var locId = $"loadout-name-{Loadout.ID}";
        var name = Loc.GetString(locId);

        if (name == locId && PreviewEntity != null)
            name = _entity.GetComponent<MetaDataComponent>(PreviewEntity.Value).EntityName;

        if (_entity.TryGetComponent<LabelComponent>(PreviewEntity, out var label))
        {
            var itemLabel = label.CurrentLabel;
            if (!string.IsNullOrEmpty(itemLabel))
                name += $" ({Loc.GetString(itemLabel)})";
        }

        return name;
    }

    private string GetDescription()
    {
        var locId = $"loadout-description-{_preference?.LoadoutName}";
        var description = Loc.GetString(locId);

        if (description == locId && PreviewEntity != null)
            description = _entity.GetComponent<MetaDataComponent>(PreviewEntity.Value).EntityDescription;

        return description;
    }
}
