# SPDX-FileCopyrightText: 2023 Fluffiest Floofers <thebluewulf@gmail.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <123355664+sleepyyapril@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

- type: entity
  id: CrateServiceReplacementColoredLights
  name: Colored Lights Crate
  parent: CrateGenericSteel
  components:
  - type: StorageFill
    contents:
      - id: BoxColoredLighttube
        amount: 2

- type: entity
  id: CrateServiceReplacementMaintenanceLights
  name: Maintenance Lights Crate
  parent: CrateGenericSteel
  components:
  - type: StorageFill
    contents:
      - id: BoxMaintenanceLightbulb
        amount: 2
