# SPDX-FileCopyrightText: 2024 Timemaster99 <57200767+Timemaster99@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Rosycup <178287475+Rosycup@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Skubman <ba.fallaria@gmail.com>
# SPDX-FileCopyrightText: 2025 VMSolidus <evilexecutive@gmail.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <123355664+sleepyyapril@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: job
  id: Clerk
  name: job-name-clerk
  description: job-description-clerk
  playTimeTracker: JobClerk
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Security
      min: 36000 # 10 hrs
    - !type:CharacterPlaytimeRequirement
      tracker: JobLawyer
      min: 36000 # 10 hours
    - !type:CharacterPlaytimeRequirement
      tracker: JobProsecutor
      min: 36000 # 10 hours


  startingGear: ClerkGear
  icon: "JobIconClerk"
  requireAdminNotify: true
  supervisors: job-supervisors-cj
  canBeAntag: false
  access:
  - Justice
  - Clerk
  - Security
  - Maintenance

- type: startingGear
  id: ClerkGear
  subGear:
  - PassengerPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitClerk
    back: ClothingBackpackFilled
    shoes: ClothingShoesBootsLaceup
    id: ClerkPDA
    ears: ClothingHeadsetJustice
  innerClothingSkirt: ClothingUniformJumpskirtClerk
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled


