# SPDX-FileCopyrightText: 2025 Vanessa Louwagie
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entityTable
  id: FillLockerSecurityGoobstation
  table: !type:AllSelector
    children:
    - id: ClothingHeadsetAltSecurityRegular
