- type: job
  id: ChiefEngineer
  name: job-name-ce
  description: job-description-ce
  playTimeTracker: JobChiefEngineer
  requirements:
    - !type:CharacterPlaytimeRequirement
      tracker: JobAtmosphericTechnician
      min: 28800 # The Den - 8 hour
#    - !type:OverallPlaytimeRequirement
#      time: 72000 # DeltaV - 20 hours
  weight: 10
  startingGear: ChiefEngineerGear
  icon: "JobIconChiefEngineer"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - Command
  - External
  - ChiefEngineer
  - Atmospherics
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellPotato

- type: startingGear
  id: ChiefEngineerGear
  subGear:
  - ChiefEngineerPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitChiefEngineer
    back: ClothingBackpackChiefEngineerFilled
    shoes: ClothingShoesColorBrown
    id: CEPDA
    ears: ClothingHeadsetCE
  innerClothingSkirt: ClothingUniformJumpskirtChiefEngineer
  satchel: ClothingBackpackSatchelChiefEngineerFilled
  duffelbag: ClothingBackpackDuffelChiefEngineerFilled

- type: startingGear
  id: ChiefEngineerPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitChiefEngineer
    head: ClothingHeadEnvirohelmChiefEngineer
    gloves: ClothingHandsGlovesEnviroglovesChiefEngineer
