# SPDX-FileCopyrightText: 2020 20kdc
# SPDX-FileCopyrightText: 2020 AJCM-git
# SPDX-FileCopyrightText: 2020 FL-OZ
# SPDX-FileCopyrightText: 2020 Hugo Laloge
# SPDX-FileCopyrightText: 2020 Peter Wedder
# SPDX-FileCopyrightText: 2020 Víctor Aguilera Puerto
# SPDX-FileCopyrightText: 2020 ike709
# SPDX-FileCopyrightText: 2021 Elijahrane
# SPDX-FileCopyrightText: 2021 Paul Ritter
# SPDX-FileCopyrightText: 2021 Swept
# SPDX-FileCopyrightText: 2021 Vera Aguilera Puerto
# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2022 Moony
# SPDX-FileCopyrightText: 2022 Morber
# SPDX-FileCopyrightText: 2022 Rane
# SPDX-FileCopyrightText: 2022 Sissel
# SPDX-FileCopyrightText: 2022 Veritius
# SPDX-FileCopyrightText: 2023 Chief-Engineer
# SPDX-FileCopyrightText: 2023 Colin-Tel
# SPDX-FileCopyrightText: 2023 Debug
# SPDX-FileCopyrightText: 2023 DrSmugleaf
# SPDX-FileCopyrightText: 2023 Emisse
# SPDX-FileCopyrightText: 2023 Fluffiest Floofers
# SPDX-FileCopyrightText: 2023 PHCodes
# SPDX-FileCopyrightText: 2023 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2023 PrPleGoo
# SPDX-FileCopyrightText: 2023 coolmankid12345
# SPDX-FileCopyrightText: 2023 randy10122
# SPDX-FileCopyrightText: 2024 DEATHB4DEFEAT
# SPDX-FileCopyrightText: 2024 Fansana
# SPDX-FileCopyrightText: 2024 FoxxoTrystan
# SPDX-FileCopyrightText: 2024 Nairod
# SPDX-FileCopyrightText: 2024 flyingkarii
# SPDX-FileCopyrightText: 2025 Eagle-0
# SPDX-FileCopyrightText: 2025 John Willis
# SPDX-FileCopyrightText: 2025 SixplyDev
# SPDX-FileCopyrightText: 2025 Skubman
# SPDX-FileCopyrightText: 2025 Timfa
# SPDX-FileCopyrightText: 2025 VMSolidus
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: MIT AND AGPL-3.0-or-later

- type: job
  id: ChiefEngineer
  name: job-name-ce
  description: job-description-ce
  playTimeTracker: JobChiefEngineer
  requirements:
    - !type:CharacterDepartmentTimeRequirement # Den - Engineering dept time requirement
      department: Engineering
      min: 144000 # The Den - 40 hours
    - !type:CharacterPlaytimeRequirement
      tracker: JobAtmosphericTechnician
      min: 28800 # The Den - 8 hours
#    - !type:OverallPlaytimeRequirement
#      time: 72000 # DeltaV - 20 hours
  weight: 10
  startingGear: ChiefEngineerGear
  icon: "JobIconChiefEngineer"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - Command
  - External
  - ChiefEngineer
  - Atmospherics
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellPotato

- type: startingGear
  id: ChiefEngineerGear
  subGear:
  - ChiefEngineerPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitChiefEngineer
    back: ClothingBackpackChiefEngineerFilled
    shoes: ClothingShoesColorBrown
    id: CEPDA
    ears: ClothingHeadsetAltEngineering # Goobstation
  innerClothingSkirt: ClothingUniformJumpskirtChiefEngineer
  satchel: ClothingBackpackSatchelChiefEngineerFilled
  duffelbag: ClothingBackpackDuffelChiefEngineerFilled

- type: startingGear
  id: ChiefEngineerPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitChiefEngineer
    head: ClothingHeadEnvirohelmChiefEngineer
    gloves: ClothingHandsGlovesEnviroglovesChiefEngineer
