# SPDX-FileCopyrightText: 2025 Eightballll
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  id: BaseStationLawGameshow
  abstract: true
  components: 
  - type: SiliconLawProvider
    laws: GameshowLawset