- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Arena
  - Asterisk
 # - Core - 02/22/24
  - Edge
  - Glacier
#  - Hammurabi - 02/22/24
#  - Lighthouse
  - Pebble
#  - Saltern - commented pending rework
  - Shoukou
#  - Submarine
  - Tortuga
  - TheHive
#  - Gax - im so sorry this wasn't commented out
#  - Rad - im so sorry this wasn't commented out
#  - Meta
#  - Box
#  - Lambda - awaiting review
#  - Bagel - awaiting review
#  - Europa
