# SPDX-FileCopyrightText: 2022 Kara <lunarautomaton6@gmail.com>
# SPDX-FileCopyrightText: 2022 Leon Friedrich <60421075+ElectroJr@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Pancake <Pangogie@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <123355664+sleepyyapril@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

#Wizard outfit startingGear definitions.
- type: startingGear
  id: WizardBlueGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorDarkBlue
    back: ClothingBackpackFilled
    head: ClothingHeadHatWizard
    outerClothing: ClothingOuterWizard
    shoes: ClothingShoesWizard
    id: PassengerPDA
    ears: ClothingHeadsetService
  innerClothingSkirt: ClothingUniformJumpskirtColorDarkBlue
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

- type: startingGear
  id: WizardRedGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorRed
    back: ClothingBackpackFilled
    head: ClothingHeadHatRedwizard
    outerClothing: ClothingOuterWizardRed
    shoes: ClothingShoesWizard
    id: PassengerPDA
    ears: ClothingHeadsetService
  innerClothingSkirt: ClothingUniformJumpskirtColorRed
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

- type: startingGear
  id: WizardVioletGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorPurple
    back: ClothingBackpackFilled
    head: ClothingHeadHatVioletwizard
    outerClothing: ClothingOuterWizardViolet
    shoes: ClothingShoesWizard
    id: PassengerPDA
    ears: ClothingHeadsetService
  innerClothingSkirt: ClothingUniformJumpskirtColorPurple
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

- type: startingGear
  id: WizardHardsuitGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorPurple
    back: ClothingBackpackFilled
    outerClothing: ClothingOuterHardsuitWizard
    shoes: ClothingShoesWizard
    id: PassengerPDA
    ears: ClothingHeadsetService
  innerClothingSkirt: ClothingUniformJumpskirtColorPurple
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
