# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2022 Morb
# SPDX-FileCopyrightText: 2022 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2022 Rane
# SPDX-FileCopyrightText: 2022 Sissel
# SPDX-FileCopyrightText: 2022 Veritius
# SPDX-FileCopyrightText: 2023 Colin-Tel
# SPDX-FileCopyrightText: 2023 DrSmugleaf
# SPDX-FileCopyrightText: 2023 Fluffiest Floofers
# SPDX-FileCopyrightText: 2023 MWKane
# SPDX-FileCopyrightText: 2023 PrPleGoo
# SPDX-FileCopyrightText: 2023 Velcroboy
# SPDX-FileCopyrightText: 2023 brainfood1183
# SPDX-FileCopyrightText: 2024 DEATHB4DEFEAT
# SPDX-FileCopyrightText: 2024 Fansana
# SPDX-FileCopyrightText: 2024 FoxxoTrystan
# SPDX-FileCopyrightText: 2025 Radezolid
# SPDX-FileCopyrightText: 2025 Skubman
# SPDX-FileCopyrightText: 2025 VMSolidus
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: job
  id: Boxer
  name: job-name-boxer
  description: job-description-boxer
  playTimeTracker: JobBoxer
  startingGear: BoxerGear
  icon: "JobIconBoxer"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Theatre # DeltaV - Add Theatre access
  - Boxer # DeltaV - Add Boxer access
  special: # Nyanotrasen - BoxerComponent, see Content.Server/Nyanotrasen/Abilities/Boxer/Boxer/BoxerComponent.cs
  - !type:AddTraitSpecial
    traits:
    - MartialArtist

- type: startingGear
  id: BoxerGear
  subGear:
  - BoxerPlasmamanGear
  equipment:
    jumpsuit: UniformShortsRed
    back: ClothingBackpackFilled
    id: BoxerPDA
    ears: ClothingHeadsetService
    gloves: ClothingHandsGlovesBoxingRed
    shoes: ClothingShoesColorRed
    belt: ClothingBeltChampion
  innerClothingSkirt: UniformShortsRedWithTop
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

- type: startingGear
  id: BoxerPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitBoxing
    head: ClothingHeadEnvirohelmBoxing
    # No envirogloves, use the boxing gloves instead
