- type: job
  id: SalvageSpecialist
  name: job-name-salvagespec
  description: job-description-salvagespec
  playTimeTracker: JobSalvageSpecialist
  requirements:
    - !type:CharacterPlaytimeRequirement
      tracker: JobCargoTechnician # DeltaV - Logistics Department replacing Cargo
      min: 7200 # The Den - 2 hour
  antagAdvantage: 3 # DeltaV - Reduced TC: External Access + Free hardsuit and weapons
  icon: "JobIconShaftMiner"
  startingGear: SalvageSpecialistGear
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External

- type: startingGear
  id: SalvageSpecialistGear
  subGear:
  - SalvageSpecialistPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSalvageSpecialist
    back: ClothingBackpackSalvageFilled
    shoes: ClothingShoesBootsSalvage
    id: SalvagePDA
    ears: ClothingHeadsetCargo
  satchel: ClothingBackpackSatchelSalvageFilled
  duffelbag: ClothingBackpackDuffelSalvageFilled

- type: startingGear
  id: SalvageSpecialistPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitSalvage
    head: ClothingHeadEnvirohelmSalvage
    gloves: ClothingHandsGlovesEnviroglovesSalvage
    mask: ClothingMaskGasExplorer
