# SPDX-FileCopyrightText: 2024 Angelo Fallaria <ba.fallaria@gmail.com>
# SPDX-FileCopyrightText: 2024 DEATHB4DEFEAT <77995199+DEATHB4DEFEAT@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 gluesniffler <159397573+gluesniffler@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Alice <alicecoupland45@gmail.com>
# SPDX-FileCopyrightText: 2025 Blitz <73762869+BlitzTheSquishy@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 BlueHNT <79374236+BlueHNT@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Lonofera <108367450+LonoferaRS@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Rosycup <178287475+Rosycup@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 VMSolidus <evilexecutive@gmail.com>
# SPDX-FileCopyrightText: 2025 mart <martgitomen@gmail.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <123355664+sleepyyapril@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

# Head Of Security
# Backpacks

# Belt

- type: loadout
  id: LoadoutCommandHoSJudoBelt
  category: JobsSecurityHeadOfSecurity
  cost: 6
  canBeHeirloom: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityBelt
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingBeltCorporateJudo

# Ears

# Equipment
# Head of Security Weapon Selection
# Most of these mirror the unique weapons that were previously map-specific items placed in the HoS Office.
# Or are weapons that fit a similar theme of "Rare weapons not normally seen by Security"

- type: loadout
  id: LoadoutCommandHoSPulsePistol
  category: JobsSecurityHeadOfSecurity
  cost: 0
  canBeHeirloom: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityWeapon
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - WeaponPulsePistolHoS

- type: loadout
  id: LoadoutCommandHoSWt550
  category: JobsSecurityHeadOfSecurity
  cost: 0
  canBeHeirloom: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityWeapon
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - WeaponSubMachineGunWt550HoS

- type: loadout
  id: LoadoutCommandHoSKatanaSheath
  category: JobsSecurityHeadOfSecurity
  cost: 0
  canBeHeirloom: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityWeapon
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingBeltKatanaSheathFilledHoS

- type: loadout
  id: LoadoutCommandHoSC20r
  category: JobsSecurityHeadOfSecurity
  cost: 0
  canBeHeirloom: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityWeapon
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - WeaponSubMachineGunC20rHoS

- type: loadout
  id: LoadoutCommandHoSBulldog
  category: JobsSecurityHeadOfSecurity
  cost: 0
  canBeHeirloom: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityWeapon
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - WeaponShotgunBulldogHoS

- type: loadout
  id: LoadoutCommandHoSEnergySword
  category: JobsSecurityHeadOfSecurity
  cost: 0
  canBeHeirloom: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityWeapon
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - EnergySwordHoS

- type: loadout
  id: LoadoutCommandHoSEnergyGun
  category: JobsSecurityHeadOfSecurity
  cost: 0
  canBeHeirloom: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityWeapon
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - WeaponEnergyGunMultiphase

- type: loadout
  id: LoadoutCommandHoSBRDIR25
  category: JobsSecurityHeadOfSecurity
  cost: 7 # Cracked
  canBeHeirloom: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityWeapon
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - WeaponSubMachineGunBRDIR25HoS

- type: loadout
  id: LoadoutCommandAntiqueTerminus
  category: JobsSecurityHeadOfSecurity
  cost: 0
  canBeHeirloom: true
  requirements:
  - !type:CharacterItemGroupRequirement
    group: LoadoutHeadOfSecurityWeapon
  - !type:CharacterJobRequirement
    jobs:
    - HeadOfSecurity
  items:
  - AntiqueTerminus

# Eyes

# Gloves

# Head
- type: loadout
  id: LoadoutCommandHOSHatBeret
  category: JobsSecurityHeadOfSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityHead
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingHeadHatBeretHoS

- type: loadout
  id: LoadoutCommandHOSHatHoshat
  category: JobsSecurityHeadOfSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityHead
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingHeadHatHoshat

# Id
- type: loadout
  id: LoadoutHeadOfSecurityNTPDA
  category: JobsSecurityHeadOfSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterPlaytimeRequirement
      tracker: JobHeadOfSecurity
      min: 36000 # 10 hours
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityId
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - HoSNTPDA

# Neck
- type: loadout
  id: LoadoutCommandHOSNeckMantle
  category: JobsSecurityHeadOfSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityNeck
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingNeckMantleHOS

- type: loadout
  id: LoadoutCommandHOSNeckCloak
  category: JobsSecurityHeadOfSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityNeck
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingNeckCloakHos

# Mask

# Outer
- type: loadout
  id: LoadoutCommandHOSOuterWinterUnarmored
  category: JobsSecurityHeadOfSecurity
  cost: 0
  exclusive: true
  requirements:
  - !type:CharacterItemGroupRequirement
    group: LoadoutHeadOfSecurityOuter
  - !type:CharacterJobRequirement
    jobs:
    - HeadOfSecurity
  items:
  - ClothingOuterWinterHoSUnarmored

- type: loadout
  id: LoadoutCommandHOSOuterWinter
  category: JobsSecurityHeadOfSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityOuter
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingOuterWinterHoS

- type: loadout
  id: LoadoutCommandHOSOuterTrench
  category: JobsSecurityHeadOfSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityOuter
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingOuterCoatHoSTrench

- type: loadout
  id: LoadoutCommandHOSOuterArmorHosSamurai
  category: JobsSecurityHeadOfSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityOuter
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingOuterArmorHosSamurai

# Shoes
- type: loadout
  id: LoadoutCommandHOSShoesBootsWinter
  category: JobsSecurityHeadOfSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityShoes
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingShoesBootsWinterHeadOfSecurity

# Uniforms
- type: loadout
  id: LoadoutUniformJumpskirtHoSBlue
  category: JobsSecurityHeadOfSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityUniforms
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingUniformJumpskirtHoSBlue

- type: loadout
  id: LoadoutUniformJumpskirtHoSGrey
  category: JobsSecurityHeadOfSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityUniforms
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingUniformJumpskirtHoSGrey

- type: loadout
  id: LoadoutCommandHOSJumpsuitAlt
  category: JobsSecurityHeadOfSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityUniforms
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingUniformJumpsuitHoSAlt

- type: loadout
  id: LoadoutCommandHOSJumpsuitBlue
  category: JobsSecurityHeadOfSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityUniforms
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingUniformJumpsuitHoSBlue

- type: loadout
  id: LoadoutCommandHOSJumpsuitGrey
  category: JobsSecurityHeadOfSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityUniforms
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingUniformJumpsuitHoSGrey

- type: loadout
  id: LoadoutCommandHOSJumpsuitParade
  category: JobsSecurityHeadOfSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityUniforms
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingUniformJumpsuitHoSParadeMale

- type: loadout
  id: LoadoutCommandHOSJumpsuitFormal
  category: JobsSecurityHeadOfSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityUniforms
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingUniformJumpsuitHosFormal

- type: loadout
  id: LoadoutCommandHOSJumpskirtAlt
  category: JobsSecurityHeadOfSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityUniforms
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingUniformJumpskirtHoSAlt

- type: loadout
  id: LoadoutCommandHOSJumpskirtParade
  category: JobsSecurityHeadOfSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityUniforms
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingUniformJumpskirtHoSParadeMale

- type: loadout
  id: LoadoutCommandHOSJumpskirtFormal
  category: JobsSecurityHeadOfSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityUniforms
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingUniformJumpskirtHosFormal

# Trinkets
- type: loadout
  id: LoadoutHoSCigarCase
  category: JobsSecurityHeadOfSecurity
  cost: 0
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityTrinkets
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - CigarRobustCase
