# SPDX-FileCopyrightText: 2025 John Willis
# SPDX-FileCopyrightText: 2025 MajorMoth
# SPDX-FileCopyrightText: 2025 RosySaturniidae
# SPDX-FileCopyrightText: 2025 SixplyDev
# SPDX-FileCopyrightText: 2025 Skubman
# SPDX-FileCopyrightText: 2025 Timfa
# SPDX-FileCopyrightText: 2025 sleepyyapril
# SPDX-FileCopyrightText: 2026 Kellaris
#
# SPDX-License-Identifier: MIT AND AGPL-3.0-or-later

- type: job
  id: Magistrate
  name: Magistrate
  description: "Ensure Space Law is being followed, Uphold Justice and Legality, Hold Hearings and Trials, Follow SOP, Ensure Command is Following Space Law."
  playTimeTracker: JobMagistrate
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Command
      min: 72000 # 20 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Security
      min: 144000 # The Den - 40 hours
    - !type:CharacterPlaytimeRequirement
      tracker: JobWarden
      min: 14400 # The Den - 4 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Logistics
      min: 36000 # The Den - 10 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Engineering
      min: 36000 # The Den - 10 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Medical
      min: 36000 # The Den - 10 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Epistemics
      min: 36000 # The Den - 10 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Civilian
      min: 36000 # The Den - 10 hours
  weight: 20
  startingGear: MagistrateGear
  icon: "JobIconMagistrate"
  requireAdminNotify: true
  joinNotifyCrew: true
  whitelisted: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - BasicAllAccess
  access:
  - CentralCommand
  - Magistrate
  - ChiefJustice
  - Prosecutor
  - Clerk
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellMedium

- type: startingGear
  id: MagistrateGear
  subGear:
  - MagistratePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMagistrate
    shoes: ClothingShoesLeather
    gloves: ClothingHandsGlovesColorWhite
    id: MagistratePDA #den
    ears: ClothingHeadsetMagistrate
    pocket1: UniqueMagistrateLockerTeleporter

- type: startingGear
  id: MagistratePlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitMagistrate
    head: ClothingHeadEnvirohelmMagistrate
    gloves: ClothingHandsGlovesEnviroglovesWhite
