# SPDX-FileCopyrightText: 2025 Eagle-0
# SPDX-FileCopyrightText: 2025 MajorMoth
# SPDX-FileCopyrightText: 2025 RosySaturniidae
# SPDX-FileCopyrightText: 2025 SixplyDev
# SPDX-FileCopyrightText: 2025 Skubman
# SPDX-FileCopyrightText: 2025 Timfa
# SPDX-FileCopyrightText: 2025 Vanessa
# SPDX-FileCopyrightText: 2025 astriloqua
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: MIT AND AGPL-3.0-or-later

- type: job
  id: NanotrasenRepresentative
  name: Nanotrasen Representative
  description: "Represent NT, send reports back to them on the station's situation, inform the heads of anything CentComm orders them to do."
  playTimeTracker: JobNanotrasenRepresentative
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Command
      min: 54000 # 15 hours
  weight: 20
  startingGear: NanotrasenRepresentativeGear
  icon: "JobIconNanotrasenRepresentative"
  requireAdminNotify: true
  joinNotifyCrew: true
  whitelisted: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - BasicAllAccess
  access:
  - CentralCommand
  - NanotrasenRepresentative
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellMedium

- type: startingGear
  id: NanotrasenRepresentativeGear
  subGear:
  - NanotrasenRepresentativePlasmamanGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: NanorepPDA
    jumpsuit: ClothingUniformJumpsuitNanotrasenRepresentative
    ears: ClothingHeadsetAltCentCom
    pocket1: UniqueNanorepLockerTeleporter

- type: startingGear
  id: NanotrasenRepresentativePlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitNanotrasenRepresentative
    head: ClothingHeadEnvirohelmNanotrasenRepresentative
    gloves: ClothingHandsGlovesEnviroglovesBlack
