# SPDX-FileCopyrightText: 2023 Moony <moony@hellomouse.net>
# SPDX-FileCopyrightText: 2023 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 deltanedas <39013340+deltanedas@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Carolyn3114 <136143032+Carolyn3114@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 DEATHB4DEFEAT <77995199+DEATHB4DEFEAT@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Debug <49997488+DebugOk@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Ed <96445749+TheShuEd@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Emisse <99158783+Emisse@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Fansana <116083121+Fansana@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Fansana <fansana95@googlemail.com>
# SPDX-FileCopyrightText: 2024 Flareguy <78941145+Flareguy@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Flareguy <78941145+flareguy@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 FoxxoTrystan <45297731+FoxxoTrystan@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Julian Giebel <juliangiebel@live.de>
# SPDX-FileCopyrightText: 2024 Ubaser <134914314+UbaserB@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Velcroboy <107660393+IamVelcroboy@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Ichaie <167008606+Ichaie@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Rane <60792108+Elijahrane@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Rosycup <178287475+Rosycup@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 VMSolidus <evilexecutive@gmail.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <123355664+sleepyyapril@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: entity
  id: BaseStation
  abstract: true
  components:
    - type: StationData

- type: entity
  id: BaseRandomStation
  abstract: true
  components:
    - type: StationRandomTransform

- type: entity
  id: BaseStationCargo
  abstract: true
  components:
    - type: StationBankAccount
    - type: StationCargoOrderDatabase
    - type: StationCargoBountyDatabase

- type: entity
  id: BaseStationJobsSpawning
  abstract: true
  components:
    - type: StationJobs
      availableJobs: {}
    - type: StationSpawning

- type: entity
  id: BaseStationRecords
  abstract: true
  components:
    - type: StationRecords

- type: entity
  id: BaseStationArrivals
  abstract: true
  components:
    - type: StationArrivals

- type: entity
  id: BaseStationGateway
  abstract: true
  components:
    - type: GatewayGenerator

- type: entity
  id: BaseStationShuttles
  abstract: true
  components:
    - type: StationCargoShuttle
      path: /Maps/Shuttles/cargo.yml
    - type: GridSpawn
      groups:
        trade:
          addComponents:
          - type: ProtectedGrid
          # If you comment out the tradestation, make sure to also set cargo.tradestation_spawns_in_ftl_map to TRUE
          - type: TradeStation
          paths:
          - /Maps/Shuttles/trading_outpost.yml
        mining:
          paths:
          - /Maps/Shuttles/pathfinder.yml
        # Spawn last
        ruins:
          hide: true
          nameGrid: true
          minCount: 2
          maxCount: 2
          stationGrid: false
          paths:
          - /Maps/Ruins/_DV/biodome_satellite.yml
          - /Maps/Ruins/_DV/derelict.yml
          - /Maps/Ruins/_DV/djstation.yml
          - /Maps/Ruins/_DV/old_ai_sat.yml
          - /Maps/Ruins/_DV/relaystation.yml
          - /Maps/Ruins/_DV/whiteship_ancient.yml
          - /Maps/Ruins/_DV/whiteship_bluespacejumper.yml

- type: entity
  id: BaseStationShuttlesCargoOnly
  abstract: true
  components:
    - type: StationCargoShuttle
      path: /Maps/Shuttles/cargo.yml
    - type: GridSpawn
      groups:
        trade:
          addComponents:
            - type: ProtectedGrid
          # If you comment out the tradestation, make sure to also set cargo.tradestation_spawns_in_ftl_map to TRUE
            - type: TradeStation
          paths:
            - /Maps/Shuttles/trading_outpost.yml
- type: entity
  id: BaseStationShuttlesSalvageOnly
  abstract: true
  components:
    - type: GridSpawn
      groups:
        mining:
          addComponents:
          - type: ProtectedGrid
          paths:
          - /Maps/Shuttles/pathfinder.yml
        ruins:
          hide: true
          nameGrid: true
          minCount: 2
          maxCount: 2
          stationGrid: false
          paths:
          - /Maps/Ruins/_DV/biodome_satellite.yml
          - /Maps/Ruins/_DV/derelict.yml
          - /Maps/Ruins/_DV/djstation.yml
          - /Maps/Ruins/_DV/old_ai_sat.yml
          - /Maps/Ruins/_DV/relaystation.yml
          - /Maps/Ruins/_DV/whiteship_ancient.yml
          - /Maps/Ruins/_DV/whiteship_bluespacejumper.yml

- type: entity
  id: BaseStationShuttlesCore
  abstract: true
  components:
    - type: GridSpawn
      groups:
        cargo:
          paths:
          - /Maps/Shuttles/cargo_core.yml
        mining:
          paths:
          - /Maps/Shuttles/pathfinder.yml
        ruins:
          hide: true
          nameGrid: true
          minCount: 2
          maxCount: 2
          stationGrid: false
          paths:
          - /Maps/Ruins/_DV/biodome_satellite.yml #Delta V - Move to DV folder
          - /Maps/Ruins/_DV/derelict.yml #Delta V - Move to DV folder
          - /Maps/Ruins/_DV/djstation.yml #Delta V - Move to DV folder
          - /Maps/Ruins/_DV/old_ai_sat.yml #Delta V - Move to DV folder
          - /Maps/Ruins/_DV/relaystation.yml #Delta V - Move to DV folder
          - /Maps/Ruins/_DV/whiteship_ancient.yml #Delta V - Move to DV folder
          - /Maps/Ruins/_DV/whiteship_bluespacejumper.yml #Delta V - Move to DV folder

- type: entity
  id: BaseStationCentcomm
  abstract: true
  components:
    - type: StationCentcomm

- type: entity
  id: BaseStationEvacuation
  abstract: true
  components:
    - type: StationEmergencyShuttle

- type: entity
  id: BaseStationAlertLevels
  abstract: true
  components:
    - type: AlertLevel
      alertLevelPrototype: stationAlerts

- type: entity
  id: BaseStationExpeditions
  abstract: true
  components:
    - type: SalvageExpeditionData

- type: entity
  id: BaseStationMagnet
  abstract: true
  components:
    - type: SalvageMagnetData

- type: entity
  id: BaseStationSiliconLawAsimov
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: Asimov

- type: entity
  id: BaseStationSiliconLawAugustine
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: Augustine

- type: entity
  id: BaseStationSiliconLawCrewsimov
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: Crewsimov

- type: entity
  id: BaseStationNews
  abstract: true
  components:
    - type: StationNews

- type: entity
  id: BaseStationAllEventsEligible
  abstract: true
  components:
    - type: StationEventEligible # For when someone makes this more granular in the future.
