# SPDX-FileCopyrightText: 2023 Bakke <luringens@protonmail.com>
# SPDX-FileCopyrightText: 2023 Colin-Tel <113523727+Colin-Tel@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Debug <49997488+DebugOk@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Debug <sidneymaatman@gmail.com>
# SPDX-FileCopyrightText: 2024 DEATHB4DEFEAT <77995199+DEATHB4DEFEAT@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Fansana <fansana95@googlemail.com>
# SPDX-FileCopyrightText: 2024 Fluffiest Floofers <thebluewulf@gmail.com>
# SPDX-FileCopyrightText: 2024 FoxxoTrystan <trystan.garnierhein@gmail.com>
# SPDX-FileCopyrightText: 2025 Skubman <ba.fallaria@gmail.com>
# SPDX-FileCopyrightText: 2025 Timfa <timfalken@hotmail.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <123355664+sleepyyapril@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <flyingkarii@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: job
  id: Gladiator
  name: job-name-gladiator
  description: job-description-gladiator
  playTimeTracker: JobGladiator
  startingGear: NyanoGladiatorGear
  alwaysUseSpawner: true
  canBeAntag: false
  icon: "JobIconGladiator"
  supervisors: job-supervisors-security
  setPreference: true
#  whitelistRequired: true
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Security
      min: 21600
  special:
  - !type:AddTraitSpecial
    traits:
    - MartialArtist
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 3
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellPotato

- type: startingGear
  id: NyanoGladiatorGear
  subGear:
  - GladiatorPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitGladiator
    outerClothing: ClothingOuterArmorGladiator
    id: GladiatorPDA
    ears: ClothingHeadsetGrey
  innerClothingSkirt: UniformShortsRedWithTop
  #any other possessions, spawn in cell

- type: startingGear
  id: GladiatorPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitGladiator
    head: ClothingHeadEnvirohelmGladiator
    gloves: ClothingHandsGlovesEnviroglovesGladiator
