# SPDX-FileCopyrightText: 2023 Debug <sidneymaatman@gmail.com>
# SPDX-FileCopyrightText: 2023 Fluffiest Floofers <thebluewulf@gmail.com>
# SPDX-FileCopyrightText: 2024 DEATHB4DEFEAT <77995199+DEATHB4DEFEAT@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Fansana <fansana95@googlemail.com>
# SPDX-FileCopyrightText: 2024 FoxxoTrystan <trystan.garnierhein@gmail.com>
# SPDX-FileCopyrightText: 2024 Velcroboy <107660393+IamVelcroboy@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Skubman <ba.fallaria@gmail.com>
# SPDX-FileCopyrightText: 2025 VMSolidus <evilexecutive@gmail.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <123355664+sleepyyapril@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: job
  id: MartialArtist
  name: job-name-martialartist
  description: job-description-martialartist
  playTimeTracker: JobMartialArtist
  startingGear: MartialArtistGear
  icon: "JobIconMartialArtist"
  supervisors: job-supervisors-hop
  setPreference: true
#  whitelistRequired: true
  access:
  - Maintenance
  - Theatre # DeltaV - Add Theatre access
  - Boxer # DeltaV - Add Boxer access
  special:
  - !type:AddTraitSpecial
    traits:
    - MartialArtist

- type: startingGear
  id: MartialArtistGear
  subGear:
  - MartialArtistPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformMartialGi
    belt: ClothingBeltMartialBlack
    back: ClothingBackpackFilled
    id: MartialArtistPDA
    ears: ClothingHeadsetService
    shoes: ClothingShoesGeta
    gloves: ClothingHandsGlovesBoxingRed
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

- type: startingGear
  id: MartialArtistPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitMartialGi
    head: ClothingHeadEnvirohelmMartialGi
    # No envirogloves, use the boxing gloves instead
    shoes: ClothingShoesColorBlack
