# SPDX-FileCopyrightText: 2025 portfiend
#
# SPDX-License-Identifier: MIT

- type: guideEntry
  id: SequenceCooking
  name: guide-entry-cooking-food-sequence
  text: /ServerInfo/Guidebook/_DEN/Cooking/SequenceCooking.xml
