# Markings are inheriting now, so these are basically used to consolidate common species restriction patterns.
# A little bit lame way of doing it but it's probably better than redefining the list each time.

# Species that use the "standard" body/head shape.
# Excluded species: Dramatically different body/head size and shape.
# Use for: Markings that fit reasonably well on the humanoid sprite base.
# Avoid using for: Markings that look weird on snouted species. (Sides/back/top of head are fine.)

- type: marking
  abstract: true
  id: BaseMarkingSpeciesStandardHead
  speciesRestriction: [Resomi]
  invertSpeciesRestriction: true

- type: marking
  abstract: true
  id: BaseMarkingSpeciesStandardBody
  speciesRestriction: [Resomi]
  invertSpeciesRestriction: true

- type: marking
  abstract: true
  id: BaseMarkingSpeciesStandardHands
  speciesRestriction:
    # Human body
    - Arachne
    - Canid
    - Felinid
    - Human
    - Kitsune
    - Oni
    # Others
    - Arachnid
    - Feroxi
    - IPC
    - Reptilian
    - Rodentia
    - SlimePerson
    - Tajaran
    - Vulpkanin
    - Ovinia
    - Shadowkin

- type: marking
  abstract: true
  id: BaseMarkingSpeciesStandardFeet
  speciesRestriction:
    # Human body
    - Canid
    - Felinid
    - Human
    - Kitsune
    - Oni
    # Others
    - Arachnid
    - Feroxi
    - IPC
    - Reptilian
    - Rodentia
    - SlimePerson
    - Tajaran
    - Vulpkanin

# Excluded species:
# - Species with weird eye shapes/positions.
# - Species for whom changing the eye shape looks bad or makes no sense.
- type: marking
  abstract: true
  id: BaseMarkingSpeciesStandardEyes
  speciesRestriction:
  - Moth
  - Chitinid
  - Shadowkin
  - Plasmaman
  - Arachne
  - Arachnid
  - Resomi
  - IPC
  - Vox
  invertSpeciesRestriction: true

# Species that use the human head and body sprites specifically.
# Included species: Humans, demihumans, species that use human sprites.
# Use for: Markings designed for the human body.
# Avoid using for: Markings designed to be used for furry/custom-sprited species.

- type: marking
  abstract: true
  id: BaseMarkingSpeciesHumanHead
  speciesRestriction:
    - Arachne
    - Canid
    - Felinid
    - Harpy
    - Human
    - Kitsune
    - Oni
    - SlimePerson # Close enough

- type: marking
  abstract: true
  id: BaseMarkingSpeciesHumanBody
  speciesRestriction:
    - Arachne
    - Canid
    - Felinid
    - Human
    - Kitsune
    - Oni
    - SlimePerson # Close enough

# No taurs.
- type: marking
  abstract: true
  id: BaseMarkingSpeciesHumanLegs
  speciesRestriction:
    - Canid
    - Felinid
    - Human
    - Kitsune
    - Oni
    - SlimePerson # Close enough

# Face shapes.

# Included species: Species with standard-ish heads and no/short snout.
# Short snout protrudes one pixel from the head.
- type: marking
  abstract: true
  id: BaseMarkingSpeciesShortFace
  speciesRestriction:
    # Human head
    - Arachne
    - Canid
    - Felinid
    - Harpy
    - Human
    - Kitsune
    - Oni
    - SlimePerson
    # Short snout
    - Ovinia
    - Rodentia
    - Tajaran

# Included species: Species whose snouts extend 1 pixel from the head.
- type: marking
  abstract: true
  id: BaseMarkingSpeciesShortSnout
  speciesRestriction:
    - Ovinia
    - Rodentia
    - Tajaran

# Included species: Species whose snouts extend 3-4 pixels from the head.
- type: marking
  abstract: true
  id: BaseMarkingSpeciesLongSnout
  speciesRestriction:
    - Feroxi
    - Reptilian
    - Vulpkanin
