# SPDX-FileCopyrightText: 2025 portfiend
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Markings are inheriting. That means they can have parents now. Yay!

## Colors

- type: marking
  abstract: true
  id: BaseColorWhite
  coloring:
    default:
      type:
        !type:SimpleColoring
          color: "#FFFFFF"

- type: marking
  abstract: true
  id: BaseTattoo
  coloring:
    default:
      type: !type:TattooColoring
      fallbackColor: "#666666"

## Parts / complex

- type: marking
  abstract: true
  id: BaseEyes
  bodyPart: Eyes
  markingCategory: Head
  coloring:
    default:
      type:
        !type:EyeColoring
          negative: true

- type: marking
  abstract: true
  parent: [BaseSpeciesWithAss, BaseColorWhite]
  id: BaseUnderpants
  bodyPart: Underwear
  markingCategory: Underwear

- type: marking
  abstract: true
  parent: [BaseSpeciesChestStandard, BaseColorWhite]
  id: BaseUndershirt
  bodyPart: Undershirt
  markingCategory: Undershirt

## Parts / categories

- type: marking
  abstract: true
  id: BaseChest
  markingCategory: Chest
  bodyPart: Chest

- type: marking
  abstract: true
  id: BaseHead
  markingCategory: Head
  bodyPart: Head

- type: marking
  abstract: true
  id: BaseHeadTop
  markingCategory: HeadTop
  bodyPart: HeadTop

- type: marking
  abstract: true
  id: BaseHeadSide
  markingCategory: HeadSide
  bodyPart: HeadSide

- type: marking
  abstract: true
  id: BaseFace
  markingCategory: Face
  bodyPart: Face

- type: marking
  abstract: true
  id: BaseSnout
  markingCategory: Snout
  bodyPart: Snout

- type: marking
  abstract: true
  id: BaseNeckFluff
  bodyPart: NeckFluff
  markingCategory: NeckFluff

- type: marking
  abstract: true
  id: BaseTail
  markingCategory: Tail
  bodyPart: Tail

# Humanoid Markings
# Head
- type: marking
  abstract: true
  id: BaseHeadMarking
  invertSpeciesRestriction: true
  speciesRestriction: [Vox, Resomi, Shadowkin, Plasmaman, Thaven, IPC, Diona, Moth, Chitinid, Arachnid]
  bodyPart: Head
  markingCategory: Head

- type: marking
  abstract: true
  id: BaseEarrings
  invertSpeciesRestriction: true
  speciesRestriction: [Vox, Shadowkin, Plasmaman, Thaven, Moth, Chitinid, Tajaran, Rodentia, Resomi]
  bodyPart: HeadSide
  markingCategory: HeadSide

- type: marking
  abstract: true
  id: BaseEarsMarking
  invertSpeciesRestriction: true
  speciesRestriction: [Vox, Shadowkin, Plasmaman, Thaven, Moth, Chitinid, Diona, Resomi, Feroxi, Reptilian]
  bodyPart: HeadTop
  markingCategory: HeadTop

- type: marking
  abstract: true
  id: BaseSideEarsMarking
  invertSpeciesRestriction: true
  speciesRestriction: [Vox, Shadowkin, Plasmaman, Thaven, Moth, Chitinid, Diona, Resomi]
  bodyPart: HeadSide
  markingCategory: HeadSide

- type: marking
  abstract: true
  id: BaseHornsMarking
  invertSpeciesRestriction: true
  speciesRestriction: [Vox, Shadowkin, Plasmaman, Thaven, Moth, Chitinid, Diona, Resomi, Harpy, Rodentia, Kitsune, Arachnid, Canid, Tajaran, Felinid, Vulpkanin]
  bodyPart: HeadTop
  markingCategory: HeadTop

# Face
- type: marking
  abstract: true
  id: BaseFaceMarking
  invertSpeciesRestriction: true
  speciesRestriction: [Vox, Resomi, Shadowkin, Plasmaman, Thaven, IPC, Diona, Moth, Chitinid, Arachnid]
  bodyPart: Face
  markingCategory: Face

- type: marking
  abstract: true
  id: BaseFaceSnoutlessMarking
  invertSpeciesRestriction: true
  speciesRestriction: [Vox, Resomi, Shadowkin, Plasmaman, Thaven, IPC, Diona, Moth, Chitinid, Arachnid, Vulpkanin, Feroxi, Reptillian, Tajaran, Rodentia ]
  bodyPart: Face
  markingCategory: Face

# Chest
- type: marking
  abstract: true
  id: BaseChestMarking
  invertSpeciesRestriction: true
  speciesRestriction: [Vox, Resomi, Shadowkin, Plasmaman, Thaven, IPC, Diona, Moth, Chitinid]
  bodyPart: Chest
  markingCategory: Chest

# Arms and Hands
- type: marking
  abstract: true
  id: BaseRArmMarking
  invertSpeciesRestriction: true
  speciesRestriction: [Vox, Resomi, Harpy, Plasmaman, Thaven, IPC, Diona, Moth, Chitinid]
  bodyPart: RArm
  markingCategory: RightArm

- type: marking
  abstract: true
  id: BaseLArmMarking
  invertSpeciesRestriction: true
  speciesRestriction: [Vox, Resomi, Harpy, Plasmaman, Thaven, IPC, Diona, Moth, Chitinid]
  bodyPart: LArm
  markingCategory: LeftArm

- type: marking
  abstract: true
  id: BaseRHandMarking
  invertSpeciesRestriction: true
  speciesRestriction: [Vox, Resomi, Harpy, Plasmaman, IPC, Diona, Moth, Chitinid]
  bodyPart: RHand
  markingCategory: RightHand

- type: marking
  abstract: true
  id: BaseLHandMarking
  invertSpeciesRestriction: true
  speciesRestriction: [Vox, Resomi, Harpy, Plasmaman, IPC, Diona, Moth, Chitinid]
  bodyPart: LHand
  markingCategory: LeftHand

# Legs and Feet
- type: marking
  abstract: true
  id: BaseRLegMarking
  invertSpeciesRestriction: true
  speciesRestriction: [Vox, Resomi, Shadowkin, Ovinia, Harpy, Plasmaman, IPC, Diona, Arachne, Moth, Chitinid]
  bodyPart: RLeg
  markingCategory: RightLeg

- type: marking
  abstract: true
  id: BaseLLegMarking
  invertSpeciesRestriction: true
  speciesRestriction: [Vox, Resomi, Shadowkin, Ovinia, Harpy, Plasmaman, IPC, Diona, Arachne, Moth, Chitinid]
  bodyPart: LLeg
  markingCategory: LeftLeg

- type: marking
  abstract: true
  id: BaseRFootMarking
  invertSpeciesRestriction: true
  speciesRestriction: [Vox, Resomi, Shadowkin, Ovinia, Harpy, Plasmaman, Tajaran, IPC, Diona, Arachne, Moth, Chitinid]
  bodyPart: RFoot
  markingCategory: RightFoot

- type: marking
  abstract: true
  id: BaseLFootMarking
  invertSpeciesRestriction: true
  speciesRestriction: [Vox, Resomi, Shadowkin, Ovinia, Harpy, Plasmaman, Tajaran, IPC, Diona, Arachne, Moth, Chitinid]
  bodyPart: LFoot
  markingCategory: LeftFoot

# Tails
- type: marking
  abstract: true
  id: BaseTailMarking
  invertSpeciesRestriction: true
  speciesRestriction: [Vox, Resomi, Shadowkin, Plasmaman, Thaven, Diona, Moth, Chitinid, Arachnid, Arachne]
  bodyPart: Tail
  markingCategory: Tail

# Cyberlimbs
## (These are basic IPC parts, but they're also prosthetic markings for other species.)

# Excluded species:
# - Species who do not have arms.
# - Species for whom arm prosthetics would not fit on their sprite.
# - Species without skin and flesh.
# NEVER exclude IPC from this list. This is also their body sprite.
# TODO: Make custom prosthetic sprites for Moth and Chitinid and then add them to this list.
- type: marking
  abstract: true
  parent: BaseSpeciesIPC
  id: BaseArmsCyberlimb
  invertSpeciesRestriction: true
  speciesRestriction:
  - Diona
  - Harpy
  - Plasmaman
  - Resomi
  - Vox

# Excluded species:
# - Species who do not have legs.
# - Species for whom leg prosthetics would not fit on their sprite.
# - Species without skin and flesh.
# NEVER exclude IPC from this list. This is also their body sprite.
# TODO: Make custom prosthetic sprites for Moth and Chitinid and then add them to this list.
- type: marking
  abstract: true
  parent: BaseSpeciesIPC
  id: BaseLegsCyberlimb
  invertSpeciesRestriction: true
  speciesRestriction:
  - Arachne
  - Diona
  - Harpy
  - Ovinia
  - Plasmaman
  - Resomi
  - Shadowkin
  - Vox
