# SPDX-FileCopyrightText: 2020 DamianX
# SPDX-FileCopyrightText: 2020 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2020 Swept
# SPDX-FileCopyrightText: 2025 Vanessa Louwagie
#
# SPDX-License-Identifier: AGPL-3.0-or-later
