using System.Linq;
using Content.Shared._DEN.StationRecords;
using Content.Shared.Roles;
using Content.Shared.StationRecords;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;


namespace Content.Client._DEN.StationRecords;

[GenerateTypedNameReferences]
public sealed partial class StationJobsConsoleWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public event Action<string>? OnJobAdd; // Frontier
    public event Action<string>? OnJobSubtract; // Frontier

    public StationJobsConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this); // Frontier
    }

    public void UpdateState(StationJobsConsoleState state)
    {
        if (state.JobList is null || state.JobSlots is null)
            return;

        JobListing.Visible = true;
        PopulateJobsContainer(state.JobList, state.JobSlots);
    }

    private void PopulateJobsContainer(IReadOnlyDictionary<string, uint?> jobList, IReadOnlyDictionary<string, uint?> jobSlots)
    {
        JobListing.RemoveAllChildren();
        foreach (var (job, amount) in jobList)
        {
            if (amount < 0 || amount is null)
                continue;

            if (!_prototype.TryIndex<JobPrototype>(job, out var jobProto))
                continue;

            string jobName = jobProto.LocalizedName;

            var jobEntry = new StationJobsConsoleJobRow(jobProto)
            {
                JobName = { Text = jobName },
                JobAmount = { Text = amount.ToString() },
                JobSlots = { Text = "(" + jobSlots.FirstOrDefault(a => a.Key == job).Value + ")" }
            };

            jobEntry.DecreaseJobSlot.OnPressed += (args) => { OnJobSubtract?.Invoke(job); };
            jobEntry.IncreaseJobSlot.OnPressed += (args) => { OnJobAdd?.Invoke(job); };
            JobListing.AddChild(jobEntry);
        }
    }
}
