using Content.Shared._DEN.StationRecords;
using Content.Shared.Roles;
using Content.Shared.StationRecords;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;


namespace Content.Client._DEN.StationRecords;

[GenerateTypedNameReferences]
public sealed partial class StationJobsConsoleWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public event Action<string>? OnJobAdd; // Frontier
    public event Action<string>? OnJobSubtract; // Frontier

    public StationJobsConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this); // Frontier
    }

    public void UpdateState(StationJobsConsoleState state)
    {
        // Frontier: job list, ship advertisements
        if (state.JobList != null)
        {
            JobListing.Visible = true;
            PopulateJobsContainer(state.JobList);
        }
    }

    private void PopulateJobsContainer(IReadOnlyDictionary<string, uint?> jobList)
    {
        JobListing.RemoveAllChildren();
        foreach (var (job, amount) in jobList)
        {
            Logger.Debug("title: " + job + " amount: " + amount);
            // Skip overflow jobs.
            if (amount < 0 || amount is null)
                continue;

            // Get proper job names when possible
            string jobName;
            if (_prototype.TryIndex<JobPrototype>(job, out var jobProto))
                jobName = jobProto.LocalizedName;
            else
                jobName = job;

            var jobEntry = new StationJobsConsoleJobRow()
            {
                JobName = { Text = jobName },
                JobAmount = { Text = amount.ToString() },
            };
            jobEntry.DecreaseJobSlot.OnPressed += (args) => { OnJobSubtract?.Invoke(job); };
            jobEntry.IncreaseJobSlot.OnPressed += (args) => { OnJobAdd?.Invoke(job); };
            JobListing.AddChild(jobEntry);
        }
    }
}
