using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._DEN.StationRecords;


[GenerateTypedNameReferences]
public sealed partial class StationJobsConsoleJobRow : PanelContainer
{
    public StationJobsConsoleJobRow()
    {
        RobustXamlLoader.Load(this);
    }
}

