# SPDX-FileCopyrightText: 2023 Velcroboy
# SPDX-FileCopyrightText: 2023 chromiumboy
# SPDX-FileCopyrightText: 2023 rosieposie
# SPDX-FileCopyrightText: 2024 DEATHB4DEFEAT
# SPDX-FileCopyrightText: 2024 Debug
# SPDX-FileCopyrightText: 2024 SimpleStation14
# SPDX-FileCopyrightText: 2024 Timemaster99
# SPDX-FileCopyrightText: 2024 TsjipTsjip
# SPDX-FileCopyrightText: 2024 VMSolidus
# SPDX-FileCopyrightText: 2024 metalgearsloth
# SPDX-FileCopyrightText: 2025 Skubman
# SPDX-FileCopyrightText: 2025 Solaris
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: entity
  parent: BaseItem
  id: AccessConfigurator
  name: access configurator
  description: Used to modify the access level requirements for airlocks and other lockable devices.
  components:
    - type: EmitSoundOnLand
      sound:
        path: /Audio/Items/multitool_drop.ogg
    - type: Sprite
      sprite: Objects/Tools/access_configurator.rsi
      state: icon
    - type: Item
      size: Small
    - type: Clothing
      sprite: Objects/Tools/access_configurator.rsi
      quickEquip: false
      slots:
        - Belt
    - type: AccessOverrider
      accessLevels:
      - Armory
      - Atmospherics
      - BasicSilicon
      - Borg
      #- Brig #Delta V: Removed Brig Access
      - Boxer #Delta V: Add Boxer Access
      - Detective
      - Captain
      - Cargo
      - Chapel
      - Chemistry
      - ChiefEngineer
      - ChiefMedicalOfficer
      - Clown #Delta V: Add Clown Access
      - Corpsman # DeltaV: Add Corpsman access
      - Command
      - Engineering
      - External
      - HeadOfPersonnel
      - HeadOfSecurity
      - Hydroponics
      - Janitor
      - Kitchen
      - Lawyer
      - Library #Delta V: Add Library Access
      - Maintenance
      - Medical
      - Mime #Delta V: Add Mime Access
      - Musician #Delta V: Add Musician Access
      - Paramedic # Delta V - adds Paramedic access
      - Psychologist #Delta V: Add Psychologist Access
      - Quartermaster
      - Reporter #Delta V: Add Reporter Access
      - Research
      - ResearchDirector
      - Robotics # DeltaV: Robotics access
      - Salvage
      - Security
      - Service
      - StationAi
      - Theatre
      - Zookeeper #Delta V: Add Zookeeper Access
      - ChiefJustice  #Delta V: Add Chief Justice Access
      - Prosecutor  #Delta V: Add Prosecutor Access
      - Justice  #Delta V: Add Justice Access
      - Clerk  #Delta V: Add Clerk Access
      privilegedIdSlot:
        name: id-card-console-privileged-id
        ejectSound: /Audio/Machines/id_swipe.ogg
        insertSound: /Audio/Weapons/Guns/MagIn/batrifle_magin.ogg
        ejectOnBreak: true
        swap: false
        whitelist:
          components:
          - IdCard
      denialSound:
        path: /Audio/Machines/custom_deny.ogg
      doAfter: 0.5
    - type: UserInterface
      interfaces:
        enum.AccessOverriderUiKey.Key:
          type: AccessOverriderBoundUserInterface
    - type: ActivatableUI
      key: enum.AccessOverriderUiKey.Key
      requiresComplex: true
      requireActiveHand: false
      singleUser: true
    - type: ItemSlots
    - type: ContainerContainer
      containers:
        AccessOverrider-privilegedId: !type:ContainerSlot
    - type: Fixtures
      fixtures:
        fix1:
          shape:
            !type:PhysShapeAabb
            bounds: "-0.25,-0.25,0.25,0.25"
          density: 12
          mask:
          - ItemMask
          restitution: 0.3
          friction: 0.2

- type: entity
  parent: AccessConfigurator
  id: AccessConfiguratorUniversal
  name: universal access configurator
  suffix: Admin
  description: A modified access configurator used only by the mythical Administrator.
  components:
  - type: Sprite
    sprite: Objects/Tools/universal_access_configurator.rsi
  - type: Clothing
    sprite: Objects/Tools/universal_access_configurator.rsi
  - type: AccessOverrider
    accessLevels:
    # WizDen
    - Armory
    - Atmospherics
    - Bar
    - BasicSilicon
    - Borg
    - Brig
    - Detective
    - Captain
    - Cargo
    - CentralCommand
    - Chapel
    - Chemistry
    - ChiefEngineer
    - ChiefMedicalOfficer
    - Command
    - Engineering
    - External
    - HeadOfPersonnel
    - HeadOfSecurity
    - Hydroponics
    - Janitor
    - Kitchen
    - Lawyer
    - Maintenance
    - Medical
    - NuclearOperative
    - Quartermaster
    - Research
    - ResearchDirector
    - Salvage
    - Security
    - Service
    - StationAi
    - SyndicateAgent
    - Theatre
    # Delta-V
    - Boxer
    - ChiefJustice
    - Clerk
    - Clown
    - Corpsman
    - DV-SpareSafe
    - Justice
    - Library
    - Mantis
    - Mime
    - Musician
    - Orders
    - Prosecutor
    - Psychologist
    - Reporter
    - Robotics
    - Zookeeper
    # EE
    - SAN
    # Goobstation
    - BlueshieldOfficer
    - Magistrate
    - NanotrasenRepresentative
    # Nyanotrasen
    - Mail
    privilegedIdSlot:
      name: id-card-console-privileged-id
      ejectSound: /Audio/Machines/id_swipe.ogg
      insertSound: /Audio/Weapons/Guns/MagIn/batrifle_magin.ogg
      ejectOnBreak: true
      swap: false
      whitelist:
        components:
        - IdCard
    denialSound:
      path: /Audio/Machines/custom_deny.ogg
    doAfter: 0.5
