# SPDX-FileCopyrightText: 2022 Cheackraze <71046427+Cheackraze@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 2022 Veritius <veritiusgaming@gmail.com>
# SPDX-FileCopyrightText: 2023 MagnusCrowe <whiterider1988@yahoo.com>
# SPDX-FileCopyrightText: 2023 Maxtone <124747282+MagnusCrowe@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Nairod <110078045+Nairodian@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Puro <103608145+PuroSlavKing@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 IProduceWidgets <107586145+IProduceWidgets@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Mnemotechnican <69920617+Mnemotechnician@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 SlamBamActionman <83650252+slambamactionman@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 VMSolidus <evilexecutive@gmail.com>
# SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 sleepyyapril <flyingkarii@gmail.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <123355664+sleepyyapril@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

# Overall play time, across all roles.
# This tracker must exist, it is used directly by PlayTimeTrackingManager
- type: playTimeTracker
  id: Overall

# Jobs
- type: playTimeTracker
  id: JobAtmosphericTechnician

- type: playTimeTracker
  id: JobBartender

- type: playTimeTracker # Used as a tracker for all borgs and midround borging.
  id: JobBorg

- type: playTimeTracker
  id: JobBotanist

- type: playTimeTracker
  id: JobCaptain

- type: playTimeTracker
  id: JobCargoTechnician

- type: playTimeTracker
  id: JobCentralCommandOfficial

- type: playTimeTracker
  id: JobChaplain

- type: playTimeTracker
  id: JobChef

- type: playTimeTracker
  id: JobChemist

- type: playTimeTracker
  id: JobChiefEngineer

- type: playTimeTracker
  id: JobChiefJustice

- type: playTimeTracker
  id: JobChiefMedicalOfficer

- type: playTimeTracker
  id: JobClown

- type: playTimeTracker
  id: JobClerk

- type: playTimeTracker
  id: JobDetective

- type: playTimeTracker
  id: JobERTChaplain

- type: playTimeTracker
  id: JobERTEngineer

- type: playTimeTracker
  id: JobERTJanitor

- type: playTimeTracker
  id: JobERTLeader

- type: playTimeTracker
  id: JobERTMedical

- type: playTimeTracker
  id: JobERTSecurity

- type: playTimeTracker
  id: JobHeadOfPersonnel

- type: playTimeTracker
  id: JobHeadOfSecurity

- type: playTimeTracker
  id: JobJanitor

- type: playTimeTracker
  id: JobLawyer

- type: playTimeTracker
  id: JobLibrarian

- type: playTimeTracker
  id: JobMedicalDoctor

- type: playTimeTracker
  id: JobMedicalIntern

- type: playTimeTracker
  id: JobMime

- type: playTimeTracker
  id: JobMusician

- type: playTimeTracker
  id: JobPassenger

- type: playTimeTracker
  id: JobParamedic

- type: playTimeTracker
  id: JobPsychologist

- type: playTimeTracker
  id: JobProsecutor

- type: playTimeTracker
  id: JobQuartermaster

- type: playTimeTracker
  id: JobReporter

- type: playTimeTracker
  id: JobResearchAssistant

- type: playTimeTracker
  id: JobResearchDirector

- type: playTimeTracker
  id: JobRoboticist

- type: playTimeTracker
  id: JobSalvageSpecialist

- type: playTimeTracker
  id: JobScientist

- type: playTimeTracker
  id: JobSecurityCadet

- type: playTimeTracker
  id: JobSecurityOfficer

- type: playTimeTracker
  id: JobSeniorEngineer

- type: playTimeTracker
  id: JobSeniorOfficer

- type: playTimeTracker
  id: JobSeniorPhysician

- type: playTimeTracker
  id: JobSeniorResearcher

- type: playTimeTracker
  id: JobServiceWorker

- type: playTimeTracker
  id: JobStationAi

- type: playTimeTracker
  id: JobStationEngineer

- type: playTimeTracker
  id: JobTechnicalAssistant

- type: playTimeTracker
  id: JobVisitor

- type: playTimeTracker
  id: JobWarden

- type: playTimeTracker
  id: JobBoxer

- type: playTimeTracker
  id: JobZookeeper

- type: playTimeTracker
  id: JobDeathSquad

- type: playTimeTracker
  id: JobCBURN