# SPDX-FileCopyrightText: 2025 VMSolidus <evilexecutive@gmail.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <123355664+sleepyyapril@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

# For use by Role Types
# Do not touch these

- type: roleType
  id: Neutral
  name: role-type-crew-aligned-name
  color: '#eeeeee'

- type: roleType
  id: SoloAntagonist
  name: role-type-solo-antagonist-name
  color: '#d82000'

- type: roleType
  id: TeamAntagonist
  name: role-type-team-antagonist-name
  color: '#d82000'

- type: roleType
  id: FreeAgent
  name: role-type-free-agent-name
  color: '#ffff00'

- type: roleType
  id: Familiar
  name: role-type-familiar-name
  color: '#6495ed'

- type: roleType
  id: Silicon
  name: role-type-silicon-name
  color: '#6495ed'

- type: roleType
  id: SiliconAntagonist
  name: role-type-silicon-antagonist-name
  color: '#c832e6'
