# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2022 Mervill
# SPDX-FileCopyrightText: 2022 Morb
# SPDX-FileCopyrightText: 2022 Morber
# SPDX-FileCopyrightText: 2022 Peptide90
# SPDX-FileCopyrightText: 2022 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2022 Sissel
# SPDX-FileCopyrightText: 2022 Veritius
# SPDX-FileCopyrightText: 2022 Zymem
# SPDX-FileCopyrightText: 2022 dontbetank
# SPDX-FileCopyrightText: 2022 mirrorcult
# SPDX-FileCopyrightText: 2023 Colin-Tel
# SPDX-FileCopyrightText: 2023 DrSmugleaf
# SPDX-FileCopyrightText: 2023 PrPleGoo
# SPDX-FileCopyrightText: 2023 Velcroboy
# SPDX-FileCopyrightText: 2023 lzk
# SPDX-FileCopyrightText: 2023 potato1234_x
# SPDX-FileCopyrightText: 2024 DEATHB4DEFEAT
# SPDX-FileCopyrightText: 2024 Fansana
# SPDX-FileCopyrightText: 2024 FoxxoTrystan
# SPDX-FileCopyrightText: 2025 Shaman
# SPDX-FileCopyrightText: 2025 SixplyDev
# SPDX-FileCopyrightText: 2025 Skubman
# SPDX-FileCopyrightText: 2025 Timfa
# SPDX-FileCopyrightText: 2025 VMSolidus
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: job
  id: Librarian
  name: job-name-librarian
  description: job-description-librarian
  playTimeTracker: JobLibrarian
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Epistemics
      min: 3600
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterSpeciesRequirement
          inverted: true
          species:
            - IPC
        - !type:CharacterTraitRequirement
          traits:
            - AnomalousPositronics
        - !type:CharacterTraitRequirement
          inverted: true
          traits:
            - ShadowkinBlackeye
  startingGear: LibrarianGear
  icon: "JobIconLibrarian"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance
  - Library
  special:
  - !type:AddComponentSpecial
    components:
    - type: Psionic
      powerSlots: 1 # TheDen - This only means that they don't start generating glimmer until they gain a second slot-taking power (they have one no-glimmer slot like all psychics)
    - type: InnatePsionicPowers
      powersToAdd: # TheDen - They have no innate slot-taking powers, so they need 100 Potentia to gain a new power
        - XenoglossyPower # Doesn't take a power slot
        - TelepathyPower # Doesn't take a power slot


- type: startingGear
  id: LibrarianGear
  subGear:
  - LibrarianPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLibrarian
    back: ClothingBackpackLibrarianFilled
    shoes: ClothingShoesBootsLaceup
    outerClothing: ClothingOuterCoatRnd
    id: LibrarianPDA
    ears: ClothingHeadsetScience
    pocket1: BookPsionicsGuidebook
    pocket2: HandLabeler
  innerClothingSkirt: ClothingUniformJumpskirtLibrarian
  satchel: ClothingBackpackSatchelLibrarianFilled
  duffelbag: ClothingBackpackDuffelLibrarianFilled

- type: startingGear
  id: LibrarianPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitAncientVoid
    head: ClothingHeadEnvirohelmAncientVoid
    gloves: ClothingHandsGlovesEnviroglovesPrototype
