# SPDX-FileCopyrightText: 2025 Velcroboy
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entityTable
  id: FillServiceGenericDV
  table: !type:AllSelector
    children:
    - id: LunchboxServiceFilledRandom
