# SPDX-FileCopyrightText: 2024 John Space
# SPDX-FileCopyrightText: 2024 gluesniffler
# SPDX-FileCopyrightText: 2025 Solstice
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: latheRecipe
  id: GrenadeFlashBang
  result: GrenadeFlashBang
  completetime: 3
  materials:
    Steel: 100
    Plastic: 100

# Mech Weapons
- type: latheRecipe
  id: WeaponMechCombatImmolationGun
  result: WeaponMechCombatImmolationGun
  category: MechWeapons
  completetime: 10
  materials:
    Steel: 2800
    Plastic: 1000
    Plasma: 750
    Glass: 500

- type: latheRecipe
  id: WeaponMechCombatSolarisLaser
  result: WeaponMechCombatSolarisLaser
  category: MechWeapons
  completetime: 10
  materials:
    Steel: 1650
    Plastic: 300
    Plasma: 250
    Glass: 200

- type: latheRecipe
  id: WeaponMechCombatFiredartLaser
  result: WeaponMechCombatFiredartLaser
  category: MechWeapons
  completetime: 10
  materials:
    Steel: 1200
    Plastic: 200
    Plasma: 150
    Glass: 50

- type: latheRecipe
  id: WeaponMechCombatUltraRifle
  result: WeaponMechCombatUltraRifle
  category: MechWeapons
  completetime: 10
  materials:
    Steel: 1000
    Plastic: 200

- type: latheRecipe
  id: WeaponMechCombatShotgun
  result: WeaponMechCombatShotgun
  category: MechWeapons
  completetime: 10
  materials:
    Steel: 1600
    Plastic: 550

- type: latheRecipe
  id: WeaponMechCombatShotgunIncendiary
  result: WeaponMechCombatShotgunIncendiary
  category: MechWeapons
  completetime: 10
  materials:
    Steel: 1500
    Plastic: 800
    Plasma: 300

- type: latheRecipe
  id: WeaponMechCombatDisabler
  result: WeaponMechCombatDisabler
  category: MechWeapons
  completetime: 10
  materials:
    Steel: 750
    Glass: 250
    Plastic: 300

- type: latheRecipe
  id: WeaponMechCombatFlashbangLauncher
  result: WeaponMechCombatFlashbangLauncher
  category: MechWeapons
  completetime: 10
  materials:
    Steel: 1200
    Glass: 300
    Plastic: 450

- type: latheRecipe
  id: WeaponMechCombatMissileRack8
  result: WeaponMechCombatMissileRack8
  category: MechWeapons
  completetime: 10
  materials:
    Steel: 2500
    Glass: 1500
    Plastic: 750

- type: latheRecipe
  id: MechEquipmentKineticAccelerator
  result: WeaponMechIndustrialKineticAccelerator
  category: MechEquipment
  completetime: 10
  materials:
    Steel: 1500
    Glass: 750
    Silver: 150

# Ammo

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineShotgunLeverRifleEmpty
  result: MagazineShotgunLeverRifleEmpty
  materials:
    Steel: 25

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineShotgunLeverRifle
  result: MagazineShotgunLeverRifle
  materials:
    Steel: 240

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxShotgunHighCaliber
  result: MagazineBoxShotgunHighCaliber
  materials:
    Steel: 480

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxShotgunSlugHighCaliber
  result: MagazineBoxShotgunSlugHighCaliber
  materials:
    Steel: 480
    Plastic: 160

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxShotgunIncendiaryHighCaliber
  result: MagazineBoxShotgunIncendiaryHighCaliber
  materials:
    Steel: 160
    Plastic: 320

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxShotgunUraniumHighCaliber
  result: MagazineBoxShotgunUraniumHighCaliber
  materials:
    Plastic: 640
    Uranium: 480

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxShotgunBeanbagHighCaliber
  result: MagazineBoxShotgunBeanbagHighCaliber
  materials:
    Steel: 320
    Plastic: 240

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxShotgunPracticeHighCaliber
  result: MagazineBoxShotgunPracticeHighCaliber
  materials:
    Steel: 160
