# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: alternateJobTitle
  id: Captain
  titles:
  - job-name-alternate-capitan
  - job-name-alternate-queen
  - job-name-alternate-commander
