# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: MIT

# Blueshield Officer
- type: alternateJobTitle
  id: DefaultBlueshieldOfficer
  jobId: BlueshieldOfficer
  titles:
  - job-name-alternate-honor-guard
  - job-name-alternate-bodyguard

# Magistrate
- type: alternateJobTitle
  id: DefaultMagistrate
  jobId: Magistrate
  titles:
  - job-name-alternate-chief-justice