# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: MIT

- type: alternateJobTitle
  id: DefaultScientist
  jobId: Scientist
  titles:
  - job-name-alternate-lab-tech
  - job-name-alternate-xenoarch
  - job-name-alternate-researcher

- type: alternateJobTitle
  id: DefaultRoboticist
  jobId: Roboticist
  titles:
  - job-name-alternate-positronic-technician
  - job-name-alternate-mech-technician
  - job-name-alternate-cyborg-specialist
