# SPDX-FileCopyrightText: 2025 ASaltySeabass
# SPDX-FileCopyrightText: 2025 Jakumba
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: MIT

- type: alternateJobTitle
  id: DefaultScientist
  jobId: Scientist
  titles:
  - job-name-alternate-lab-tech
  - job-name-alternate-xenoarch
  - job-name-alternate-researcher
  - job-name-alternate-acolyte

- type: alternateJobTitle
  id: DefaultRoboticist
  jobId: Roboticist
  titles:
  - job-name-alternate-positronic-technician
  - job-name-alternate-mech-technician
  - job-name-alternate-cyborg-specialist
  - job-name-alternate-bionic-engineer
  - job-name-alternate-biomechanical-engineer

- type: alternateJobTitle
  id: DefaultResearchDirector
  jobId: ResearchDirector
  titles:
    - job-name-alternate-chief-scientist
    - job-name-alternate-head-researcher
    - job-name-alternate-research-coordinator
    - job-name-alternate-research-director

- type: alternateJobTitle
  id: DefaultForensicMantis
  jobId: ForensicMantis
  titles:
    - job-name-alternate-inquisitor

- type: alternateJobTitle
  id: DefaultChaplain
  jobId: Chaplain
  titles:
    - job-name-alternate-cleric
    - job-name-alternate-priest
    - job-name-alternate-priestess
    - job-name-alternate-curate
    - job-name-alternate-officiant

- type: alternateJobTitle
  id: DefaultSeniorResearcher
  jobId: SeniorResearcher
  titles:
    - job-name-alternate-mystic

- type: alternateJobTitle
  id: DefaultLibrarian
  jobId: Librarian
  titles:
    - job-name-alternate-librarian
    - job-name-alternate-scholar
    - job-name-alternate-archivist

- type: alternateJobTitle
  id: DefaultResearchAssistant
  jobId: ResearchAssistant
  titles:
  - job-name-alternate-lab-assistant
  - job-name-alternate-initiate
  - job-name-alternate-novitiate