# SPDX-FileCopyrightText: 2025 Jakumba
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: MIT

- type: alternateJobTitle
  id: DefaultScientist
  jobId: Scientist
  titles:
  - job-name-alternate-lab-tech
  - job-name-alternate-xenoarch
  - job-name-alternate-researcher
  - job-name-alternate-acolyte

- type: alternateJobTitle
  id: DefaultRoboticist
  jobId: Roboticist
  titles:
  - job-name-alternate-positronic-technician
  - job-name-alternate-mech-technician
  - job-name-alternate-cyborg-specialist

- type: alternateJobTitle
  id: DefaultResearchDirector
  jobId: ResearchDirector
  titles:
    - job-name-alternate-chief-scientist
    - job-name-alternate-head-researcher
    - job-name-alternate-research-coordinator
    - job-name-alternate-research-director

- type: alternateJobTitle
  id: DefaultForensicMantis
  jobId: ForensicMantis
  titles:
    - job-name-alternate-inquisitor
