- type: alternateJobTitle
  id: DefaultSecurityOfficer
  jobId: SecurityOfficer
  titles:
  - job-name-alternate-patrolman
  - job-name-alternate-patrolperson
  - job-name-alternate-patrolwoman
  - job-name-alternate-watchman
  - job-name-alternate-watchperson
  - job-name-alternate-watchwoman