# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: MIT

- type: alternateJobTitle
  id: DefaultHeadOfSecurity
  jobId: HeadOfSecurity
  titles:
  - job-name-alternate-sheriff
  - job-name-alternate-security-director
  - job-name-alternate-security-chief
  - job-name-alternate-daimyo

- type: alternateJobTitle
  id: DefaultSecurityOfficer
  jobId: SecurityOfficer
  titles:
  - job-name-alternate-deputy
  - job-name-alternate-peacekeeper
  - job-name-alternate-security-guard
  - job-name-alternate-nt-trooper

- type: alternateJobTitle
  id: DefaultSeniorOfficer
  jobId: SeniorOfficer
  titles:
  - job-name-alternate-ranger
  - job-name-alternate-senior-guard
  - job-name-alternate-senior-trooper

- type: alternateJobTitle
  id: DefaultCorpsman
  jobId: Brigmedic
  titles:
  - job-name-alternate-brigmedic
  - job-name-alternate-field-medic

- type: alternateJobTitle
  id: DefaultDetective
  jobId: Detective
  titles:
  - job-name-alternate-inspector
  - job-name-alternate-investigator

- type: alternateJobTitle
  id: DefaultWarden
  jobId: Warden
  titles:
  - job-name-alternate-armorer
  - job-name-alternate-armourer
  - job-name-alternate-deputy-head
  - job-name-alternate-deputy-chief
  - job-name-alternate-assistant-security-director
  - job-name-alternate-deputy-security-director
  - job-name-alternate-bailiff
  - job-name-alternate-marshal
