# SPDX-FileCopyrightText: 2025 Jakumba
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: MIT

- type: alternateJobTitle
  id: DefaultPassenger
  jobId: Passenger
  titles:
  - job-name-alternate-assistant
  - job-name-alternate-tourist
  - job-name-alternate-off-duty
  - job-name-alternate-fisher
  - job-name-alternate-fish-enthusiast
  - job-name-alternate-angler

- type: alternateJobTitle
  id: DefaultBartender
  jobId: Bartender
  titles:
  - job-name-alternate-mixologist
  - job-name-alternate-barista
  - job-name-alternate-waiter
  - job-name-alternate-tapster
  - job-name-alternate-alcoholic-technician

- type: alternateJobTitle
  id: DefaultBotanist
  jobId: Botanist
  titles:
  - job-name-alternate-farmer
  - job-name-alternate-gardener
  - job-name-alternate-hydroponics-technician

- type: alternateJobTitle
  id: DefaultChef
  jobId: Chef
  titles:
  - job-name-alternate-baker
  - job-name-alternate-butcher
  - job-name-alternate-cuisinic-technician
  - job-name-alternate-culinarian

- type: alternateJobTitle
  id: DefaultClown
  jobId: Clown
  titles:
  - job-name-alternate-jester
  - job-name-alternate-fool
  - job-name-alternate-harlequin
  - job-name-alternate-entertainer

- type: alternateJobTitle
  id: DefaultMusician
  jobId: Musician
  titles:
  - job-name-alternate-dj
  - job-name-alternate-performer
  - job-name-alternate-singer
  - job-name-alternate-composer
  - job-name-alternate-guitarist
  - job-name-alternate-pianist
  - job-name-alternate-drummer

- type: alternateJobTitle
  id: DefaultGladiator
  jobId: Gladiator
  titles:
  - job-name-alternate-combatant
  - job-name-alternate-performance-fighter

- type: alternateJobTitle
  id: DefaultMime
  jobId: Mime
  titles:
  - job-name-alternate-mummer
  - job-name-alternate-interpretive-dancer
  - job-name-alternate-mute

- type: alternateJobTitle
  id: DefaultHeadOfPersonnel
  jobId: HeadOfPersonnel
  titles:
  - job-name-alternate-bureaucratic-ambassador
  - job-name-alternate-paperwork-enthusiast
  - job-name-alternate-station-inspector
  - job-name-alternate-recruiter
  - job-name-alternate-head-of-service
  - job-name-alternate-service-director

- type: alternateJobTitle
  id: DefaultReporter
  jobId: Reporter
  titles:
    - job-name-alternate-journalist
    - job-name-alternate-correspondent
    - job-name-alternate-radio-host
