- type: alternateJobTitle
  id: DefaultPassenger
  jobId: Passenger
  titles:
  - job-name-alternate-tourist
  - job-name-alternate-off-duty

- type: alternateJobTitle
  id: DefaultBartender
  jobId: Bartender
  titles:
  - job-name-alternate-mixologist

- type: alternateJobTitle
  id: DefaultChef
  jobId: Chef
  titles:
  - job-name-alternate-baker
  - job-name-alternate-butcher

- type: alternateJobTitle
  id: DefaultClown
  jobId: Clown
  titles:
  - job-name-alternate-jester
  - job-name-alternate-fool