# SPDX-FileCopyrightText: 2024 Radezolid <snappednexus@gmail.com>
# SPDX-FileCopyrightText: 2024 sleepyyapril <flyingkarii@gmail.com>
# SPDX-FileCopyrightText: 2025 Rosycup <178287475+Rosycup@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 SixplyDev <einlichen@gmail.com>
# SPDX-FileCopyrightText: 2025 Skubman <ba.fallaria@gmail.com>
# SPDX-FileCopyrightText: 2025 Timfa <timfalken@hotmail.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <123355664+sleepyyapril@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: job
  id: AdministrativeAssistant
  name: job-name-admin-assistant
  description: job-description-admin-assistant
  playTimeTracker: JobAdminAssistant
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Engineering
      min: 10800 # 3 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Logistics
      min: 10800 # 3 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Medical
      min: 10800 # 3 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Civilian
      min: 10800 # 3 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Security
      min: 10800 # 3 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Epistemics
      min: 10800 # 3 hours
  startingGear: AdminAssistantGear
  icon: "JobIconAdminAssitant"
  supervisors: job-supervisors-command
  canBeAntag: false
  access:
    - Command
    - Maintenance
  special:
    - !type:AddImplantSpecial
      implants: [MindShieldImplant]
    - !type:AddComponentSpecial
      components:
      - type: CommandStaff

- type: startingGear
  id: AdminAssistantGear
  subGear:
  - AdminAssistantPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAdminAssistant
    id: AdminAssistantPDA
    ears: ClothingHeadsetAltAdminAssist
    shoes: ClothingShoesLeather
  innerClothingSkirt: ClothingUniformJumpskirtAdminAssistant

- type: startingGear
  id: AdminAssistantPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitAdminAssistant
    head: ClothingHeadEnvirohelmAdminAssistant
    gloves: ClothingHandsGlovesEnviroglovesAdminAssistant
