# SPDX-FileCopyrightText: 2025 John Willis <143434770+CerberusWolfie@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <123355664+sleepyyapril@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: playTimeTracker
  id: JobBlueshieldOfficer

- type: playTimeTracker
  id: JobNanotrasenRepresentative

- type: playTimeTracker
  id: JobMagistrate
