# SPDX-FileCopyrightText: 2023 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 brainfood1183 <113240905+brainfood1183@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 lzk <124214523+lzk228@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 GNUtopia <93669372+GNUtopia@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <123355664+sleepyyapril@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: startingGear
  id: PirateGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackPirateFilled
    head: ClothingHeadBandBlack
    shoes: ClothingShoesBootsLaceup
    id: PiratePDA
    belt: ClothingBeltUtility
    pocket1: AppraisalTool
  innerClothingSkirt: ClothingUniformJumpsuitPirate
  satchel: ClothingBackpackPirateFilled
  duffelbag: ClothingBackpackPirateFilled

- type: startingGear
  id: PirateCaptainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackPirateFilled
    head: ClothingHeadHatPirate
    shoes: ClothingShoesBootsLaceup
    id: PiratePDA
    belt: ClothingBeltUtility
    pocket1: AppraisalTool
    pocket2: EnergyCutlass
    outerClothing: ClothingOuterCoatPirate
  innerClothingSkirt: ClothingUniformJumpskirtColorLightBrown
  satchel: ClothingBackpackPirateFilled
  duffelbag: ClothingBackpackPirateFilled

- type: startingGear
  id: PirateFirstmateGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackPirateFilled
    head: ClothingHeadHatPirateTricorn
    shoes: ClothingShoesBootsLaceup
    id: PiratePDA
    belt: ClothingBeltUtility
    pocket1: AppraisalTool
    outerClothing: ClothingOuterCoatGentle
  innerClothingSkirt: ClothingUniformJumpsuitPirate
  satchel: ClothingBackpackPirateFilled
  duffelbag: ClothingBackpackPirateFilled
