# SPDX-FileCopyrightText: 2021 Mith-randalf
# SPDX-FileCopyrightText: 2021 Peptide90
# SPDX-FileCopyrightText: 2021 Swept
# SPDX-FileCopyrightText: 2022 Emisse
# SPDX-FileCopyrightText: 2022 Fishfish458
# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2022 Rane
# SPDX-FileCopyrightText: 2022 fishfish458
# SPDX-FileCopyrightText: 2022 ike709
# SPDX-FileCopyrightText: 2022 theashtronaut
# SPDX-FileCopyrightText: 2023 Adrian16199
# SPDX-FileCopyrightText: 2023 Alekshhh
# SPDX-FileCopyrightText: 2023 Chief-Engineer
# SPDX-FileCopyrightText: 2023 Colin-Tel
# SPDX-FileCopyrightText: 2023 Fluffiest Floofers
# SPDX-FileCopyrightText: 2023 Jeff
# SPDX-FileCopyrightText: 2023 Kevin Zheng
# SPDX-FileCopyrightText: 2023 Kit0vras
# SPDX-FileCopyrightText: 2023 Lei Yunxing
# SPDX-FileCopyrightText: 2023 Nim
# SPDX-FileCopyrightText: 2023 Puro
# SPDX-FileCopyrightText: 2023 Scribbles0
# SPDX-FileCopyrightText: 2023 SpaceCat
# SPDX-FileCopyrightText: 2023 Tad "Taddy" Johnson
# SPDX-FileCopyrightText: 2023 Velcroboy
# SPDX-FileCopyrightText: 2023 Whisper
# SPDX-FileCopyrightText: 2023 metalgearsloth
# SPDX-FileCopyrightText: 2024 Agoichi
# SPDX-FileCopyrightText: 2024 Aviu00
# SPDX-FileCopyrightText: 2024 BonkTrauma
# SPDX-FileCopyrightText: 2024 Flareguy
# SPDX-FileCopyrightText: 2024 FoxxoTrystan
# SPDX-FileCopyrightText: 2024 HappyRoach
# SPDX-FileCopyrightText: 2024 Icepick
# SPDX-FileCopyrightText: 2024 IlyaElDunaev
# SPDX-FileCopyrightText: 2024 LankLTE
# SPDX-FileCopyrightText: 2024 Lonely Fox
# SPDX-FileCopyrightText: 2024 Moomoobeef
# SPDX-FileCopyrightText: 2024 Nairod
# SPDX-FileCopyrightText: 2024 Nemanja
# SPDX-FileCopyrightText: 2024 Plykiya
# SPDX-FileCopyrightText: 2024 PoTeletubby
# SPDX-FileCopyrightText: 2024 SimpleStation14
# SPDX-FileCopyrightText: 2024 Ty Ashley
# SPDX-FileCopyrightText: 2024 Unkn0wn_Gh0st
# SPDX-FileCopyrightText: 2024 crazybrain23
# SPDX-FileCopyrightText: 2024 deltanedas
# SPDX-FileCopyrightText: 2024 kosticia
# SPDX-FileCopyrightText: 2024 lzk
# SPDX-FileCopyrightText: 2024 marbow
# SPDX-FileCopyrightText: 2024 starch
# SPDX-FileCopyrightText: 2024 to4no_fix
# SPDX-FileCopyrightText: 2025 Aiden
# SPDX-FileCopyrightText: 2025 Aidenkrz
# SPDX-FileCopyrightText: 2025 ArtisticRoomba
# SPDX-FileCopyrightText: 2025 Blitz
# SPDX-FileCopyrightText: 2025 BombasterDS2
# SPDX-FileCopyrightText: 2025 BramvanZijp
# SPDX-FileCopyrightText: 2025 Eagle-0
# SPDX-FileCopyrightText: 2025 Fishbait
# SPDX-FileCopyrightText: 2025 Floxington
# SPDX-FileCopyrightText: 2025 GoobBot
# SPDX-FileCopyrightText: 2025 JORJ949
# SPDX-FileCopyrightText: 2025 Jakumba
# SPDX-FileCopyrightText: 2025 Killerqu00
# SPDX-FileCopyrightText: 2025 Lincoln McQueen
# SPDX-FileCopyrightText: 2025 Lumminal
# SPDX-FileCopyrightText: 2025 MajorMoth
# SPDX-FileCopyrightText: 2025 Rosycup
# SPDX-FileCopyrightText: 2025 SX-7
# SPDX-FileCopyrightText: 2025 SX_7
# SPDX-FileCopyrightText: 2025 Solstice
# SPDX-FileCopyrightText: 2025 VMSolidus
# SPDX-FileCopyrightText: 2025 fishbait
# SPDX-FileCopyrightText: 2025 gus
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: entity
  id: LockerWardenFilledHardsuit
  suffix: Filled, Hardsuit
  parent: LockerWarden
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - !type:NestedSelector
          tableId: FillLockerWarden
        - !type:NestedSelector
          tableId: FillLockerWardenHarduit
        - !type:NestedSelector
          tableId: FillLockerWardenDEN
        - !type:NestedSelector
          tableId: FillLockerWardenDV
        - !type:NestedSelector
          tableId: FillLockerWardenFloof

- type: entity
  id: LockerWardenFilled
  suffix: Filled
  parent: LockerWarden
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - !type:NestedSelector
          tableId: FillLockerWarden
        - !type:NestedSelector
          tableId: FillLockerWardenDEN
        - !type:NestedSelector
          tableId: FillLockerWardenDV
        - !type:NestedSelector
          tableId: FillLockerWardenFloof

- type: entityTable
  id: FillLockerWarden
  table: !type:AllSelector
    children:
    - id: FlashlightSeclite
    - id: WeaponDisabler
    - id: ClothingBeltSecurityFilled
    - id: Flash
    - id: ClothingEyesGlassesSecurity
    - id: ClothingHandsGlovesCombat
    - id: ClothingShoesBootsJack
    - id: ClothingOuterCoatWarden
    - id: ClothingOuterWinterWarden
    - id: RubberStampWarden
    - id: DoorRemoteArmory
    - id: HoloprojectorSecurity
    - id: BookSpaceLaw
    - id: ClothingBackpackElectropack
      amount: 2
    - id: RemoteSignaller
      amount: 2
    - id: Binoculars

- type: entityTable
  id: FillLockerWardenHarduit
  table: !type:AllSelector
    children:
    - id: ClothingOuterHardsuitWarden
    - id: OxygenTankFilled
    - id: ClothingMaskBreath
    - id: NitrogenTankFilled # TheDen - Added NitrogenTank because not everyone breathes O2

- type: entity
  id: LockerSecurityFilled
  suffix: Filled
  parent: LockerSecurity
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - !type:NestedSelector
          tableId: FillLockerSecurity
        - !type:NestedSelector
          tableId: FillLockerSecurityGoobstation
        - !type:NestedSelector
          tableId: FillLockerSecurityDV

- type: entityTable
  id: FillLockerSecurity
  table: !type:AllSelector
    children:
    - id: FlashlightSeclite
      prob: 0.8
    - id: WeaponDisabler
    - id: ClothingUniformJumpsuitSecGrey
      prob: 0.3
    - id: ClothingHeadHelmetBasic
    - id: ClothingOuterArmorBasic
    - id: ClothingBeltSecurityFilled
    - id: Flash
      prob: 0.5
    - id: ClothingEyesGlassesSecurity
    - id: ClothingHeadsetSecurity
    - id: ClothingHandsGlovesColorBlack
    - id: ClothingShoesBootsJack
    - id: WeaponMeleeNeedle
      prob: 0.1
    - id: HoloprojectorSecurity
      prob: 0.6
    - id: BookSpaceLaw
      prob: 0.5
    - id: WeaponMeleeNeedle
      prob: 0.1
    - id: ClothingEyesHudSecurity
    - id: ClothingEyesGlassesSunglasses

- type: entity
  id: LockerBrigmedicFilled
  suffix: Corpsman, Filled # DeltaV - rename brigmedic to corpsman
  parent: LockerBrigmedic
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - !type:NestedSelector
          tableId: FillLockerBrigmedic
        - !type:NestedSelector
          tableId: FillLockerBrigmedicFloof
        - !type:NestedSelector
          tableId: FillLockerBrigmedicDV

- type: entity
  id: LockerBrigmedicFilledHardsuit
  suffix: Corpsman, Filled, Hardsuit
  parent: LockerBrigmedic
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - !type:NestedSelector
          tableId: FillLockerBrigmedic
        - !type:NestedSelector
          tableId: FillLockerBrigmedicFloof
        - !type:NestedSelector
          tableId: FillLockerBrigmedicDV
        - !type:NestedSelector
          tableId: FillLockerBrigmedicHarduitDV

- type: entityTable
  id: FillLockerBrigmedic
  table: !type:AllSelector
    children:
    - id: ClothingEyesGlassesSecurity
    - id: WeaponDisabler
    - id: TrackingImplanter
      amount: 2
    - id: BoxSterileMask
    # - id: ClothingHeadHatBeretBrigmedic - DeltaV - Removed for corpsman clothing
    # - id: ClothingOuterCoatAMG
    - id: ClothingUniformJumpsuitBrigmedic
    - id: ClothingUniformJumpskirtBrigmedic
    # - id: ClothingUniformJumpskirtOfLife
    #   prob: 0.1
    - id: MedkitFilled
    - !type:GroupSelector
      prob: 0.7
      children:
      - id: MedkitCombatFilled
        weight: 1.6
      - id: MedkitAdvancedFilled
      - id: MedkitOxygenFilled
        weight: 0.8
      - id: MedkitBruteFilled
        weight: 0.8
      - id: MedkitToxinFilled
        weight: 0.8
      - id: MedkitBurnFilled
        weight: 1.8
    - id: ClothingNeckCloakMoth #bzzz Moth-pocalypse
      prob: 0.15

- type: entity
  id: LockerDetectiveFilled
  suffix: Filled
  parent: LockerDetective
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - !type:NestedSelector
          tableId: FillLockerDetective
        - !type:NestedSelector
          tableId: FillLockerDetectiveDV


- type: entityTable
  id: FillLockerDetective
  table: !type:AllSelector
    children:
    # - id: ClothingEyesGlassesNoir # NYI - TODO: Cherry-pick https://github.com/space-wizards/space-station-14/pull/36923
    - id: ClothingHeadHatDetGadget
    - id: ClothingNeckTieDet
    - id: ClothingOuterVestDetective
    - id: ClothingOuterCoatDetectiveLoadout
    - id: FlippoEngravedLighter
    - id: FlashlightSeclite
    - id: ForensicScanner
    - id: LogProbeCartridge
    - id: BoxForensicPad
    - id: DrinkDetFlask
    - id: ClothingHandsGlovesForensic
    - id: RubberStampDetective
    - id: HoloprojectorSecurity
    - id: BoxEvidenceMarkers
    - id: HandLabeler

- type: entity
  id: ClosetBombFilled
  parent: ClosetBomb
  suffix: Filled
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillClosetBomb

- type: entityTable
  id: FillClosetBomb
  table: !type:AllSelector
    children:
    - id: ClothingHeadHelmetBombSuit
    - id: ClothingOuterSuitBomb
    - id: Wirecutter
    - id: Screwdriver
    - id: Multitool
      prob: 0.5

- type: entity
  parent: GunSafe
  id: GunSafeDisabler
  name: disabler safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeDisabler

- type: entityTable
  id: FillGunSafeDisabler
  table: !type:AllSelector
    children:
    - id: WeaponDisabler
      amount: 5

- type: entity
  parent: GunSafe
  id: GunSafePistolMk58
  name: mk58 safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafePistolMk58

- type: entityTable
  id: FillGunSafePistolMk58
  table: !type:AllSelector
    children:
    - id: WeaponPistolMk58
      amount: 4
    - id: MagazinePistol
      amount: 8

- type: entity
  parent: GunSafe
  id: GunSafeRifleLecter
  name: lecter safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeRifleLecter

- type: entityTable
  id: FillGunSafeRifleLecter
  table: !type:AllSelector
    children:
    - id: WeaponRifleLecter
      amount: 2
    - id: MagazineRifle
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeSubMachineGunDrozd
  name: drozd safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeSubMachineGunDrozd

- type: entityTable
  id: FillGunSafeSubMachineGunDrozd
  table: !type:AllSelector
    children:
    - id: WeaponSubMachineGunDrozd
      amount: 2
    - id: MagazinePistolSubMachineGun
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeShotgunEnforcer
  name: enforcer safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeShotgunEnforcer

- type: entityTable
  id: FillGunSafeShotgunEnforcer
  table: !type:AllSelector
    children:
    - id: WeaponShotgunEnforcer
      amount: 2
    - id: MagazineShotgun
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeShotgunKammerer
  name: kammerer safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeShotgunKammerer

- type: entityTable
  id: FillGunSafeShotgunKammerer
  table: !type:AllSelector
    children:
    - id: WeaponShotgunKammerer
      amount: 2
    - id: BoxLethalshot
      amount: 4

- type: entity
  id: GunSafeSubMachineGunWt550
  suffix: WT550
  parent: GunSafe
  name: wt550 safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeSubMachineGunWt550

- type: entityTable
  id: FillGunSafeSubMachineGunWt550
  table: !type:AllSelector
    children:
    - id: WeaponSubMachineGunWt550
      amount: 2
    - id: MagazinePistolSubMachineGunTopMounted
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeLaserCarbine
  name: laser safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeLaserCarbine

- type: entityTable
  id: FillGunSafeLaserCarbine
  table: !type:AllSelector
    children:
    - id: WeaponLaserCarbine
      amount: 3

- type: entity
  id: GunSafeRifleBRDIR25
  suffix: BRDI-R25
  parent: GunSafe
  name: BRDI-R25 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunBRDIR25
      amount: 2
    - id: MagazineCaselessRifle
      amount: 4
