# SPDX-FileCopyrightText: 2025 Shaman
# SPDX-FileCopyrightText: 2025 portfiend
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  abstract: true
  parent: StripableInventoryBase
  id: RenamableStrippableBase
  components:
  - type: Renamable
  - type: UserInterface
    interfaces:
      enum.SharedRenamableInterfaceKey.Key:
        type: RenamableBoundUserInterface
      enum.StrippingUiKey.Key:
        type: StrippableBoundUserInterface

- type: entity
  save: false
  abstract: true
  id: StorableSpecies # So any species parented to this can technically be stored in a bag, if it's big enough
  components:
  - type: PseudoItem # Any species that's naturally storable will overwrite these values due to how parenting works, obviously
    shape:
      - 0,0,20,5 # 1 too wide to fit inside ClothingBackpackDuffelHolding, so only bags designed to carry people can actually fit them inside
