- type: latheRecipe
  id: MagazineMagnumEmpty
  result: MagazineMagnumEmpty
  category: Ammo
  completeTime: 5
  materials:
    Steel: 50

- type: latheRecipe
  id: MagazineMagnum
  result: MagazineMagnum
  category: Ammo
  completeTime: 5
  materials:
     Steel: 210
