- type: loadout
  id: LoadoutCommandHOSOuterLongCoat
  category: JobsSecurityHeadOfSecurity
  cost: 0
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadOfSecurityOuter
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingLongcoatHoS
