# SPDX-FileCopyrightText: 2023 Fluffiest Floofers <thebluewulf@gmail.com>
# SPDX-FileCopyrightText: 2024 sleepyyapril <***>
# SPDX-FileCopyrightText: 2025 sleepyyapril <123355664+sleepyyapril@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: latheRecipe
  id: ClothingHeadCage
  icon:
    sprite: Nyanotrasen/Clothing/Head/Hats/cage.rsi
    state: icon
  result: ClothingHeadCage
  completetime: 4
  materials:
    Steel: 400
    Bluespace: 20

- type: latheRecipe
  id: ClothingHeadHelmetInsulated
  result: ClothingHeadHelmetInsulated
  completetime: 4
  materials:
    Steel: 400
    Bluespace: 20

- type: latheRecipe
  id: ShockCollar
  icon:
    sprite: Nyanotrasen/Clothing/Neck/Misc/shock.rsi
    state: icon
  result: ShockCollar
  completetime: 2
  materials:
    Steel: 300
    Glass: 100
    Plastic: 100

- type: latheRecipe
  id: ShellSoulbreaker
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/shotgun_shell.rsi
    state: practice
  result: ShellSoulbreaker
  completetime: 4
  materials:
    Plastic: 15
    Steel: 10
    Bluespace: 10
    Glass: 5
