using Content.Client._DEN.Lobby.UI.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Lobby.UI.Loadouts;

[GenerateTypedNameReferences]
public sealed partial class LoadoutsTab : BoxContainer
{
    /// <remarks>
    /// 250 is about how wide the text "Nanotrasen Representative" is. Any smaller and it'll
    /// resize itself unpredictably.
    /// </remarks>
    private const float CategoryPanelWidth = 250f;

    public LoadoutsTab()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        var categories = new LoadoutsCategoryPanel()
        {
            HorizontalExpand = false,
            VerticalExpand = true,
            VScrollEnabled = true,
            HorizontalAlignment = HAlignment.Stretch,
            SetWidth = CategoryPanelWidth,
        };

        var itemList = new LoadoutsItemListPanel();

        LoadoutConfigPanels.AddChild(categories);
        LoadoutConfigPanels.AddChild(itemList);

        categories.OnCategorySelected += itemList.SetVisibleCategory;
        categories.SelectLoadoutCategory(null, true);
    }
    public static string GetCategoryName(string categoryId) => Loc.GetString($"loadout-category-{categoryId}");
}
