// SPDX-FileCopyrightText: 2025 portfiend
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client._DEN.Lobby.UI.Controls;
using Content.Shared.CCVar;
using Content.Shared.Clothing.Loadouts.Prototypes;
using Content.Shared.Clothing.Loadouts.Systems;
using Content.Shared.Guidebook;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Client._DEN.Lobby.UI.Loadouts;

[GenerateTypedNameReferences]
public sealed partial class LoadoutsTab : BoxContainer
{
    [Dependency] private readonly IConfigurationManager _configuration = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    /// <summary>
    ///     Fired when a loadout preference changes, prompting the character editor to update the profile.
    /// </summary>
    public event Action<LoadoutPreference>? OnPreferenceChanged;

    /// <summary>
    ///     Fired when requesting to remove unusable loadouts.
    /// </summary>
    public event Action<List<LoadoutPrototype>>? OnRemoveUnusableLoadouts;

    /// <summary>
    ///     Fired when this tab would like to open a guidebook entry.
    /// </summary>
    public event Action<List<ProtoId<GuideEntryPrototype>>>? OnOpenGuidebook;

    private int MaxPoints => _configuration.GetCVar(CCVars.GameLoadoutsPoints);
    private LoadoutPreference? CurrentlyCustomizing => CustomizationPanel.Preference;

    public LoadoutsTab()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        ItemListPanel.OnPointsUpdaated += UpdatePointsDisplay;
        ItemListPanel.OnCustomizeToggled += ToggleCustomizePreference;
        ItemListPanel.OnRemoveUnusableLoadouts += RemoveUnusableLoadouts;
        ItemListPanel.OnOpenGuidebook += OpenGuidebook;
        ItemListPanel.OnPreferenceChanged += UpdateLoadoutPreference;
        ItemListPanel.OnPreferenceChanged += p =>
        {
            // If we're equipping a new loadout
            if (p.Selected)
            {
                SetCustomizePreference(p);
                return;
            }

            // If we're unequipping the loadout that we're currently customizing
            if (CurrentlyCustomizing?.LoadoutName == p.LoadoutName)
                SetCustomizePreference(null);
        };

        CategoryPanel.OnCategorySelected += ItemListPanel.SetVisibleCategory;
        CategoryPanel.SelectLoadoutCategory(null, true);

        CustomizationPanel.OnCustomizationSaved += UpdateLoadoutPreference;
    }

    public void SetProfile(HumanoidCharacterProfile? profile)
    {
        ItemListPanel.SetProfile(profile);
        CategoryPanel.UpdateLoadoutCounts(profile);

        // If the customization panel is open, then we need to sync the panel's Preference
        // with the preference stored in the new profile.
        if (CurrentlyCustomizing?.LoadoutName != null
            && profile?.LoadoutPreferences != null
            && profile.LoadoutPreferences.Count > 0)
        {
            var newPref = profile.LoadoutPreferences
                .FirstOrDefault(p => p.LoadoutName == CurrentlyCustomizing.LoadoutName);

            if (newPref != null)
                SetCustomizePreference(newPref);
        }
    }

    public void SetCharacterDummy(EntityUid? dummy)
    {
        ItemListPanel.SetCharacterDummy(dummy);
    }

    private void SetCustomizePreference(LoadoutPreference? preference)
    {
        CustomizationPanel.Preference = preference;
        EntityUid? previewSprite = null;

        if (preference != null
            && _prototype.TryIndex<LoadoutPrototype>(preference.LoadoutName, out var loadout))
            previewSprite = ItemListPanel.GetPreviewEntity(loadout);

        CustomizationPanel.SetPreviewSprite(previewSprite);
    }

    private void ToggleCustomizePreference(LoadoutPreference preference)
    {
        var newPreference = CurrentlyCustomizing?.LoadoutName == preference.LoadoutName
            ? null
            : preference;

        SetCustomizePreference(newPreference);
    }

    public void Reset()
    {
        SetCustomizePreference(null);
        ItemListPanel.PopulateLoadouts(reset: true);
    }

    private void UpdateLoadoutPreference(LoadoutPreference preference)
    {
        OnPreferenceChanged?.Invoke(preference);
    }

    private void RemoveUnusableLoadouts()
    {
        var unusable = ItemListPanel.UnusableLoadouts;
        OnRemoveUnusableLoadouts?.Invoke(unusable);
    }

    private void UpdatePointsDisplay(int points)
    {
        PointsLabel.Text = Loc.GetString("humanoid-profile-editor-loadouts-points-label",
            ("points", points),
            ("max", MaxPoints));
        PointsBar.MaxValue = MaxPoints;
        PointsBar.Value = points;
    }

    private void OpenGuidebook(string guideEntry)
    {
        if (!_prototype.TryIndex<GuideEntryPrototype>(guideEntry, out var entry))
            return;

        var entries = new List<ProtoId<GuideEntryPrototype>>() { entry.ID };
        OnOpenGuidebook?.Invoke(entries);
    }

    public static string GetCategoryName(string categoryId) => Loc.GetString($"loadout-category-{categoryId}");
}
