# SPDX-FileCopyrightText: 2025 Stop-Signs <stopsign221@gmail.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <123355664+sleepyyapril@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <flyingkarii@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: entity
  parent: MicrowaveMachineCircuitboard
  id: AdvancedMicrowaveMachineCircuitBoard
  name: advanced microwave machine board
  components:
  - type: MachineBoard
    prototype: AdvancedMicrowave
    requirements:
      Capacitor: 2
    materialRequirements:
      Glass: 4
      Cable: 5
