# SPDX-FileCopyrightText: 2022 metalgearsloth
# SPDX-FileCopyrightText: 2022 mirrorcult
# SPDX-FileCopyrightText: 2024 DEATHB4DEFEAT
# SPDX-FileCopyrightText: 2024 Debug
# SPDX-FileCopyrightText: 2025 MajorMoth
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

name: "Labels: PR"

on:
- pull_request_target

jobs:
  labeler:
    if: github.actor != 'TheDen-Bot'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
