# SPDX-FileCopyrightText: 2025 Aiden
# SPDX-FileCopyrightText: 2025 Aidenkrz
# SPDX-FileCopyrightText: 2025 MajorMoth
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Update REUSE Headers
concurrency:
  group: reuse_action
  cancel-in-progress: false
on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  update_headers:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v4
        with:
          ref: ${{ vars.CHANGELOG_BRANCH }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tqdm

      - name: Run REUSE Header Update Script
        run: | # this should handle both normal merges and squash merges
          MERGE_SHA="${{ github.event.pull_request.merge_commit_sha }}"
          if [ -z "$MERGE_SHA" ]; then
            MERGE_SHA="${{ github.event.pull_request.head.sha }}"
          fi
          python Tools/reuse_utilities/reuse_update_headers_from_merge.py $MERGE_SHA
        working-directory: ${{ github.workspace }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: ${{ vars.REUSE_MESSAGE }}
          commit_user_name: ${{ vars.CHANGELOG_USER }}
          commit_user_email: ${{ vars.CHANGELOG_EMAIL }}
          commit_author: ${{ vars.CHANGELOG_USER }} <${{ vars.CHANGELOG_EMAIL }}>
          skip_dirty_check: false
          skip_fetch: true

